// FILE: GeometryGenerator.cs
// AUTHOR: Otakar Kočí <xkocio00@stud.fit.vut.cz>
// DATE: 2025 - 2026
// NOTE: This file is part of my Bachelor's thesis: Procedural generator of 3D voxel maps
// DESC: Contains GeometryGenerator class with its dependencies that generates geometry of chunks in columns
//          in different LODs. Uses both simple meshing for water blocks and greedy meshing for other ones.

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using Godot;
using Vector3Sys = System.Numerics.Vector3;

namespace PCGVoxelLandscapes.Scripts;

/**
 * Structure holding geometry data of single lod level of a chunk.
 */
public struct ChunkMesh
{
    public int chunkX;
    public int chunkY;
    public int chunkZ;
    
    // normal surface
    public Vector3[] vertices;
    public Vector3[] normals;
    public Vector2[] uvs;
    public int[] indices;
    
    // water surface
    public Vector3[] waterVertices;
    public Vector3[] waterNormals;
    public int[] waterIndices;
    
    public Vector3Int worldPosition;
    public bool hasGeometry;
    public bool hasWaterGeometry;
}

/**
 * Structure holding geometry for all lods of a given chunk.
 */
public struct ChunkGeometry(int lodCount)
{
    public bool hasGeometry = false;
    public ChunkMesh[] lods = new ChunkMesh[lodCount];
}

/**
 * Holds all geometry of a single chunk column.
 */
public class ChunkColumnGeometry(int chunkX, int chunkZ, int chunkCountY)
{
    public readonly int chunkX = chunkX;
    public readonly int chunkZ = chunkZ;
    public bool ready;
    public ChunkGeometry[] chunks = new ChunkGeometry[chunkCountY];
}

/**
 * Represents directions where faces are pointing.
 */
public enum DIRECTION : byte
{
    UP,
    DOWN,
    FORWARD,
    BACK,
    LEFT,
    RIGHT
}

/**
 * Voxel mask for fast lookup in the Greedy meshing algorithm.
 */
public struct VoxelMask(VoxelType type, bool render) : IEquatable<VoxelMask>
{
    public readonly VoxelType voxelType = type;
    public readonly bool shouldRender = render;

    public static bool operator ==(VoxelMask a, VoxelMask b)
    {
        return a.voxelType == b.voxelType && a.shouldRender == b.shouldRender;
    }
        
    public static bool operator !=(VoxelMask a, VoxelMask b)
    {
        return !(a == b);
    }
        
    public override bool Equals(object obj)
    {
        return obj is VoxelMask other && Equals(other);
    }
        
    public override int GetHashCode()
    {
        return (int)voxelType;
    }

    public bool Equals(VoxelMask other)
    {
        return voxelType == other.voxelType;
    }
}

/**
 * Quad of geometry generated by Greedy meshing algorithm.
 */
public struct GreedyQuad(int x, int y, int z, uint width, uint height, VoxelType voxelType, float cubeSize)
{
    public readonly int x = x;
    public readonly int y = y;
    public readonly int z = z;
    public readonly uint width = width;
    public readonly uint height = height;
    public readonly VoxelType voxelType = voxelType;
    public readonly float cubeSize = cubeSize;
}

/**
 * Generates geometry from voxel data on a column - chunk basis.
 * Uses both simple meshing for water, and greedy meshing algorithm for everything else.
 * Geometry is always generated at all LOD levels.
 */
public class GeometryGenerator
{
    private static readonly DIRECTION[] _directions = 
    [
        DIRECTION.UP,
        DIRECTION.DOWN,
        DIRECTION.FORWARD,
        DIRECTION.BACK,
        DIRECTION.LEFT,
        DIRECTION.RIGHT
    ];
    
    // vertices of faces in given directions
    private static readonly Dictionary<DIRECTION, Vector3[]> _faceVertices = new()
    {
        [DIRECTION.UP] =
        [
            new(0, 1, 1),
            new(1, 1, 0),
            new(1, 1, 1),
            new(0, 1, 0)
        ],
        [DIRECTION.DOWN] =
        [
            new(1, 0, 0),
            new(0, 0, 1),
            new(1, 0, 1),
            new(0, 0, 0)
        ],
        [DIRECTION.BACK] =
        [
            new(0, 0, 1),
            new(1, 1, 1),
            new(1, 0, 1),
            new(0, 1, 1)
        ],
        [DIRECTION.FORWARD] =
        [
            new(0, 0, 0),
            new(1, 1, 0),
            new(0, 1, 0),
            new(1, 0, 0)
        ],
        [DIRECTION.RIGHT] =
        [
            new(1, 1, 0),
            new(1, 0, 1),
            new(1, 1, 1),
            new(1, 0, 0)
        ],
        [DIRECTION.LEFT] =
        [
            new(0, 1, 1),
            new(0, 0, 0),
            new(0, 1, 0),
            new(0, 0, 1)
        ]
    };
    
    // world and voxel configuration
    private readonly int voxelsPerMeter;
    private readonly float voxelSize;
    private readonly int chunkVoxelSize;
    private readonly int lodCount;
    // generation speed tracking
    private readonly List<long> lodGenerationTimes;
    private readonly Lock lodGenerationTimesLock;
    private readonly int maxLodGenerationTimes = 1000;
    private long currentSumLodGenerationTimes;
    
    
    public GeometryGenerator(int voxelsPerMeter, int chunkVoxelSize, int lodCount)
    {
        this.voxelsPerMeter = voxelsPerMeter;
        voxelSize = 1f / voxelsPerMeter;
        this.chunkVoxelSize = chunkVoxelSize;
        this.lodCount = lodCount;
        lodGenerationTimes = [];
        lodGenerationTimesLock = new Lock();
    }
    
    /**
     * Returns average time in ms it takes to generate single LOD level of a chunk.
     */
    public long GetAverageChunkLodGenerationTime()
    {
        lock (lodGenerationTimesLock)
        {
            if (lodGenerationTimes.Count == 0)
                return 0;
            return currentSumLodGenerationTimes / lodGenerationTimes.Count;
        }
    }

    /**
     * Generates geometry for all chunks of all lods of given column.
     */
    public ChunkGeometry[] GenerateChunkColumnGeometry(ChunkColumn column)
    {
        ChunkGeometry[] chunks = new ChunkGeometry[column.chunkCountY];
        // process all chunks
        for (int y = 0; y < column.chunkCountY; y++)
        {
            ChunkGeometry chunkGeometry = new ChunkGeometry(lodCount);
            // skip processing of air only chunks as these will result in no geometry
            if (column.IsChunkCompletelyAir((uint)y))
            {
                chunks[y] = chunkGeometry;
                continue;
            }
            
            chunkGeometry.hasGeometry = true;
            // process the chunk at all LOD levels
            for (int lod = 0; lod < lodCount; lod++)
            {
                long chunkLODTimeStart = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
                chunkGeometry.lods[lod] = GenerateChunkMesh(column, column.chunkX, y, column.chunkZ, (LodLevel)lod);
                long chunkLODTotal = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() - chunkLODTimeStart;
                lock (lodGenerationTimesLock)
                {
                    if (lodGenerationTimes.Count >= maxLodGenerationTimes)
                    {
                        currentSumLodGenerationTimes -= lodGenerationTimes[0];
                        lodGenerationTimes.RemoveAt(0);
                    }
                    lodGenerationTimes.Add(chunkLODTotal);
                    currentSumLodGenerationTimes += chunkLODTotal;
                }

                // if LOD0 has no geometry, it can be skipped
                if (lod == 0 && !chunkGeometry.lods[lod].hasGeometry && !chunkGeometry.lods[lod].hasWaterGeometry)
                {
                    chunkGeometry.hasGeometry = false;
                    break;
                }
            }

            chunks[y] = chunkGeometry;
        }
        return chunks;
    }

    /**
     * Regenerates geometry for specified chunk in given column.
     * Works the same as GenerateChunkColumnGeometry, but generates lods only for the specified chunk.
     */
    public ChunkMesh[] RegenerateChunkGeometry(ChunkColumn column, int chunkY)
    {
        ChunkMesh[] lodMeshes = new ChunkMesh[lodCount];
        
        // generate all lods
        for (int lod = 0; lod < lodCount; lod++)
        {
            long chunkLODTimeStart = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            lodMeshes[lod] = GenerateChunkMesh(column, column.chunkX, chunkY, column.chunkZ, (LodLevel)lod);
            long chunkLODTotal = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() - chunkLODTimeStart;
            lock (lodGenerationTimesLock)
            {
                if (lodGenerationTimes.Count >= maxLodGenerationTimes)
                {
                    currentSumLodGenerationTimes -= lodGenerationTimes[0];
                    lodGenerationTimes.RemoveAt(0);
                }
                lodGenerationTimes.Add(chunkLODTotal);
                currentSumLodGenerationTimes += chunkLODTotal;
            }
        }
        
        return lodMeshes;
    }

    /**
     * Generates chunk geometry at specified LOD level.
     * Non-water geometry uses greedy meshing algorithm to minimize amount of geometry.
     * Water geometry uses simple meshing, as all vertices are needed for waves in the water shader.
     */
    private ChunkMesh GenerateChunkMesh(ChunkColumn column, int chunkX, int chunkY, int chunkZ, LodLevel lodLevel)
    {
        byte voxelStep = GetVoxelStepForLod(lodLevel);
        // setup collections for non-water and water geometry
        List<Vector3> vertices = [];
        List<Vector3> normals = [];
        List<Vector2> uvs = [];
        List<int> indices = [];
        int vertexOffset = 0;

        List<Vector3> waterVertices = [];
        List<Vector3> waterNormals = [];
        List<int> waterIndices = [];

        // calculate global start position, cube size and quad dimensions
        int startX = chunkX * chunkVoxelSize;
        int startY = chunkY * chunkVoxelSize;
        int startZ = chunkZ * chunkVoxelSize;
        int dimensionSize = chunkVoxelSize / voxelStep;
        float cubeSize = voxelSize * voxelStep;

        // generate geometry of non-water blocks using greedy meshing
        
        // generating quads of the mesh for all face directions
        foreach (DIRECTION direction in _directions)
        {
            // generate quads for current direction
            List<GreedyQuad> quads = GenerateGreedyQuadsForDirection(column, startX, startY, startZ, dimensionSize, cubeSize, direction, voxelStep, chunkX, chunkZ);
            // add all to the mesh
            foreach (GreedyQuad quad in quads)
            {
                AddQuadToMesh(quad, direction, startX, startY, startZ, vertices, normals, uvs, indices, ref vertexOffset); // vertex offset modified inside
            }
        }

        // generate water geometry with simple meshing, detailed vertex information needed for water waves in shader
        GenerateWaterGeometrySimple(column, chunkX, chunkY, chunkZ, voxelStep, cubeSize, waterVertices, waterNormals, waterIndices);

        // return chunk mesh structure with the geometry
        return new ChunkMesh()
        {
            chunkX = chunkX,
            chunkY = chunkY,
            chunkZ = chunkZ,
            vertices = vertices.Count > 0 ? vertices.ToArray() : null,
            normals = normals.Count > 0 ? normals.ToArray() : null,
            uvs = uvs.Count > 0 ? uvs.ToArray() : null,
            indices = indices.Count > 0 ? indices.ToArray() : null,
            waterVertices = waterVertices.Count > 0 ? waterVertices.ToArray() : null,
            waterNormals = waterNormals.Count > 0 ? waterNormals.ToArray() : null,
            waterIndices = waterIndices.Count > 0 ? waterIndices.ToArray() : null,
            worldPosition = new Vector3Int(startX / voxelsPerMeter, startY / voxelsPerMeter, startZ / voxelsPerMeter),
            hasGeometry = vertices.Count > 0,
            hasWaterGeometry = waterVertices.Count > 0
        };
    }

    /**
     * Generates water geometry by using simple voxel meshing.
     * Uses ShouldRenderWaterFace method to find out which faces need geometry, this method among many things
     * ensures that only surfaces of the water will be generated, discarding embedded faces.
     * Voxels of plants embedded in water (XXX_WATER) are treated as water voxels at higher LOD levels
     * Array of normals is collapsed into a single normal per face and needs to be extended during geometry display.
     */
    private void GenerateWaterGeometrySimple(ChunkColumn column, int chunkX, int chunkY, int chunkZ, byte voxelStep,
        float cubeSize, List<Vector3> waterVertices, List<Vector3> waterNormals, List<int> waterIndices)
    {
        // calculate boundaries
        int startX = chunkX * chunkVoxelSize;
        int startY = chunkY * chunkVoxelSize;
        int startZ = chunkZ * chunkVoxelSize;
        int endX = startX + chunkVoxelSize;
        int endY = startY + chunkVoxelSize;
        int endZ = startZ + chunkVoxelSize;

        int waterVertexOffset = 0;

        // step through voxels
        for (int x = startX; x < endX; x += voxelStep)
        {
            for (int y = startY; y < endY; y += voxelStep)
            {
                for (int z = startZ; z < endZ; z += voxelStep)
                {
                    // obtain current voxel
                    VoxelType voxelType = column.GetVoxel(x, (uint)y, z, voxelStep);
                    
                    // treat plant voxels in water as water for meshing purposes, but only at higher LOD levels
                    if (voxelStep > 1 && voxelType is VoxelType.PLANT_WATER or VoxelType.PLANT_DARK_WATER or
                            VoxelType.YELLOW_WATER or VoxelType.BROWN_WATER or VoxelType.RED_WATER or
                            VoxelType.BLUE_WATER or VoxelType.WHITE_WATER)
                    {
                        voxelType = VoxelType.WATER;
                    }

                    // water mesh only for water or water plant voxels
                    if (voxelType != VoxelType.WATER)
                    {
                        continue;
                    }

                    // for all face directions
                    foreach (DIRECTION direction in _directions)
                    {
                        // check whether this face should be rendered
                        if (!ShouldRenderWaterFace(column, x, y, z, direction, voxelStep, chunkX, chunkZ))
                            continue;
                        
                        // should be rendered
                        Vector3 directionVector = GetDirectionVectorGodot(direction);
                        Vector3 basePosition = new((x - startX) * voxelSize, (y - startY) * voxelSize, (z - startZ) * voxelSize);
                        Vector3[] vertices = _faceVertices[direction];

                        // add vertices, transformed to base position and scaled by cube size
                        waterVertices.Add(basePosition + vertices[0] * cubeSize);
                        waterVertices.Add(basePosition + vertices[1] * cubeSize);
                        waterVertices.Add(basePosition + vertices[2] * cubeSize);
                        waterVertices.Add(basePosition + vertices[3] * cubeSize);
                        // only single normal, expanded before display
                        waterNormals.Add(directionVector);
                        // uvs not needed in shader
                        // build up indices for both triangles
                        waterIndices.Add(waterVertexOffset);
                        waterIndices.Add(waterVertexOffset + 1);
                        waterIndices.Add(waterVertexOffset + 2);
                        waterIndices.Add(waterVertexOffset + 3);
                        waterIndices.Add(waterVertexOffset + 1);
                        waterIndices.Add(waterVertexOffset);

                        waterVertexOffset += 4;
                    }
                }
            }
        }
    }

    /**
     * Determines whether specified face of a water voxel should have geometry.
     * Water faces are only rendered when face is at the transition between water and air voxels.
     * Includes handling of situations when neighbor voxels are in a different column and other.
     */
    private bool ShouldRenderWaterFace(ChunkColumn column, int x, int y, int z, DIRECTION direction, byte voxelStep, int chunkX, int chunkZ)
    {
        Vector3Sys directionVector = GetDirectionVector(direction);
        
        int nX = x + (int)directionVector.X * voxelStep;
        int nY = y + (int)directionVector.Y * voxelStep;
        int nZ = z + (int)directionVector.Z * voxelStep;
        
        // render faces pointing up above world height limit
        if (direction == DIRECTION.UP && nY >= column.totalVoxelsY)
        {
            return true;
        }

        // do not render faces pointing down below y=0
        if (direction == DIRECTION.DOWN && nY < 0)
        {
            return false;
        }

        // check if chunk boundary is crossed
        int neighborChunkX = nX >= 0 ? nX / chunkVoxelSize : (nX - chunkVoxelSize + 1) / chunkVoxelSize;
        int neighborChunkZ = nZ >= 0 ? nZ / chunkVoxelSize : (nZ - chunkVoxelSize + 1) / chunkVoxelSize;

        VoxelType neighborType;

        // check for cross-column boundary (different X or Z chunk)
        if (neighborChunkX != chunkX || neighborChunkZ != chunkZ)
        {
            // crossing into a different chunk column, check neighbor
            ORIENTATION neighborOrientation = GetOrientationFromDirection(direction, neighborChunkX - chunkX, neighborChunkZ - chunkZ);
            ChunkColumn neighborColumn = column.GetNeighbor(neighborOrientation);
            // get neighbor voxel type
            if (neighborColumn == null)
            {
                // no neighbor column - treat as air
                neighborType = VoxelType.AIR;
            }
            else
            {
                neighborType = neighborColumn.GetVoxel(nX, (uint)nY, nZ, voxelStep);
            }
        }
        else
        {
            // get neighbor voxel type from same column
            neighborType = column.GetVoxel(nX, (uint)nY, nZ, voxelStep);
        }

        // also render water when facing plants up
        if (direction == DIRECTION.UP && neighborType is VoxelType.BLUE or VoxelType.BROWN
                or VoxelType.PLANT or VoxelType.PLANT_DARK or VoxelType.RED or VoxelType.YELLOW or VoxelType.WHITE)
        {
            return true;
        }

        // water only renders faces when facing air
        return neighborType == VoxelType.AIR;
    }

    /**
     * Generates quads of geometry for given direction using greedy meshing algorithm.
     * Chunk is processed in slices perpendicular to supplied face direction.
     * Each slice generates 2D mask with information about which spots should and should not be rendered.
     * This mask is then processed and quads of optimal size are generated.
     */
    private List<GreedyQuad> GenerateGreedyQuadsForDirection(ChunkColumn column, int startX, int startY, int startZ, int dimensionSize, float cubeSize, DIRECTION direction, byte voxelStep, int chunkX, int chunkZ)
    {
        List<GreedyQuad> quads = []; // generated quads
        
        // determine dimension and slice starts for slicing of the voxel structure
        (int widthStart, int heightStart, int sliceStart) = GetDimensionStartsForDirection(direction, startX, startY, startZ);
        int sliceCount = chunkVoxelSize;
        
        // generate quads for each slice perpendicular to the direction
        for (int slice = sliceStart; slice < sliceStart + sliceCount; slice += voxelStep)
        {
            // generate slice mask
            VoxelMask[,] mask = GenerateMask(column, direction, slice, voxelStep, chunkX, chunkZ, dimensionSize, widthStart, heightStart);

            // generate quads from the mask using greedy meshing
            List<GreedyQuad> sliceQuads = GenerateQuadsFromMask(mask, direction, slice, voxelStep, cubeSize, dimensionSize, widthStart, heightStart);

            quads.AddRange(sliceQuads); // add the generated quads of this slice
        }

        return quads;
    }

    /**
     * Returns starting positions of slicing based on slicing direction.
     */
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static (int widthStart, int heightStart, int sliceStart) GetDimensionStartsForDirection(DIRECTION direction, int startX, int startY, int startZ)
    {
        switch (direction)
        {
            case DIRECTION.UP:
            case DIRECTION.DOWN:
                // XZ plane, slice along Y
                return (startX, startZ, startY);
            case DIRECTION.FORWARD:
            case DIRECTION.BACK:
                // XY plane, slice along Z
                return (startX, startY, startZ);
            default:
                // LEFT or RIGHT
                // YZ plane, slice along X
                return (startY, startZ, startX);
        }
    }

    /**
     * Generates 2D mask for given slice and direction.
     */
    private VoxelMask[,] GenerateMask(ChunkColumn column, DIRECTION direction, int slice, byte voxelStep, int chunkX, int chunkZ, int dimensionSize, int widthStart, int heightStart)
    {
        VoxelMask[,] mask = new VoxelMask[dimensionSize, dimensionSize];

        for (int i = 0; i < dimensionSize; i++) // width
        {
            for (int j = 0; j < dimensionSize; j++) // height
            {
                // convert mask to world coordinates
                int worldWidth = widthStart + i * voxelStep;
                int worldHeight = heightStart + j * voxelStep;
                (int worldX, int worldY, int worldZ) = ConvertMaskToWorldCoords(direction, worldWidth, worldHeight, slice);
                // to obtain voxel of this face
                VoxelType currentType = column.GetVoxel(worldX, (uint)worldY, worldZ, voxelStep);
                
                // check if this face should be rendered or not
                bool shouldRender = ShouldRenderFace(currentType, column, worldX, worldY, worldZ, direction, voxelStep, chunkX, chunkZ);
                mask[i, j] = new VoxelMask(currentType, shouldRender);
            }
        }

        return mask;
    }

    /**
     * Converts mask coordinates to world coordinates.
     */
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static (int x, int y, int z) ConvertMaskToWorldCoords(DIRECTION direction, int width, int height, int slice)
    {
        switch (direction)
        {
            case DIRECTION.UP:
            case DIRECTION.DOWN:
                // XZ plane, slice along Y
                return (width, slice, height);
            case DIRECTION.FORWARD:
            case DIRECTION.BACK:
                // XY plane, slice along Z
                return (width, height, slice);
            default:
                // LEFT or RIGHT
                // YZ plane, slice along X
                return (slice, width, height);
        }
    }

    /**
     * Generates quads of optimal sizes from the given 2D mask.
     */
    private static List<GreedyQuad> GenerateQuadsFromMask(VoxelMask[,] mask, DIRECTION direction, int slice, byte voxelStep, float cubeSize, int dimensionSize, int widthStart, int heightStart)
    {
        List<GreedyQuad> quads = [];
        // array of processed mask positions, early exits
        bool[,] processed = new bool[dimensionSize, dimensionSize];

        // loop through all positions in the 2D mask
        for (int i = 0; i < dimensionSize; i++) // width
        {
            for (int j = 0; j < dimensionSize; j++) // height
            {
                if (processed[i, j] || !mask[i, j].shouldRender)
                    continue; // skip if processed or when this one should not be rendered

                VoxelMask currentMask = mask[i, j];

                // current position should be rendered, find the largest quad possible
                
                // extend width of current quad as much as possible
                int width = 1;
                while (i + width < dimensionSize && !processed[i + width, j] && mask[i + width, j] == currentMask)
                {
                    width++;
                }

                // extend height of current quad as much as possible
                int height = 1;
                bool canExtendHeight = true;
                while (j + height < dimensionSize && canExtendHeight)
                {
                    // needs to verify in width as well
                    for (int w = 0; w < width; w++)
                    {
                        if (processed[i + w, j + height] || mask[i + w, j + height] != currentMask)
                        {
                            canExtendHeight = false;
                            break;
                        }
                    }
                    if (canExtendHeight)
                    {
                        height++;
                    }
                }

                // mark all cells in this quad as processed
                for (int w = 0; w < width; w++)
                {
                    for (int h = 0; h < height; h++)
                    {
                        processed[i + w, j + h] = true;
                    }
                }

                // convert mask to world coordinates
                int worldWidth = widthStart + i * voxelStep;
                int worldHeight = heightStart + j * voxelStep;
                (int worldX, int worldY, int worldZ) = ConvertMaskToWorldCoords(direction, worldWidth, worldHeight, slice);

                // create and add the quad
                GreedyQuad quad = new GreedyQuad(worldX, worldY, worldZ, (uint)width, (uint)height, currentMask.voxelType, cubeSize);
                quads.Add(quad);
            }
        }

        return quads;
    }

    /**
     * Adds given quad geometry to mesh defined by supplied lists of vertices, normals, uvs and indices.
     * Manipulates vertexOffset for correct indexing of future quads.
     */
    private void AddQuadToMesh(GreedyQuad quad, DIRECTION direction, int startX, int startY, int startZ,
        List<Vector3> vertices, List<Vector3> normals, List<Vector2> uvs, List<int> indices, ref int vertexOffset)
    {
        // calculate local base position of the quad
        Vector3 basePosition = new Vector3((quad.x - startX) * voxelSize, (quad.y - startY) * voxelSize, (quad.z - startZ) * voxelSize);
        
        // scale quad face vertices based on quad dimensions and cube size
        Vector3[] quadVertices = ScaleQuadVertices(direction, quad.width, quad.height, quad.cubeSize);
        
        Vector3 directionVector = GetDirectionVectorGodot(direction);
        
        // add vertices, apply local base position, scaling done in ScaleQuadVertices
        for (int i = 0; i < 4; i++)
        {
            vertices.Add(basePosition + quadVertices[i]);
        }
        // add single normal, expanded during geometry display
        normals.Add(directionVector);

        // obtain UV coordinates from texture atlas manager
        Vector2 atlasUV = VoxelAtlas.GetAtlasUV(quad.voxelType);
        // apply only once, expanded during geometry display
        uvs.Add(atlasUV);

        // add indices
        indices.Add(vertexOffset);
        indices.Add(vertexOffset + 1);
        indices.Add(vertexOffset + 2);

        indices.Add(vertexOffset + 3);
        indices.Add(vertexOffset + 1);
        indices.Add(vertexOffset);

        vertexOffset += 4; // increase for future quads
    }

    /**
     * Manages scaling of base face vertices to match quad dimensions.
     */
    private static Vector3[] ScaleQuadVertices(DIRECTION direction, uint width, uint height, float cubeSize)
    {
        Vector3[] quadVertices = new Vector3[4];

        // obtain base vertices for given direction, scale by current cube size
        for (int i = 0; i < 4; i++)
        {
            quadVertices[i] = _faceVertices[direction][i] * cubeSize;
        }

        // scale by width and height
        switch (direction)
        {
            case DIRECTION.UP:
                // UP face vertices: (0,1,1), (1,1,0), (1,1,1), (0,1,0)
                // scales in X and Z directions
                // vertices 1 and 2 have X=1, scale by width
                quadVertices[1].X *= width;
                quadVertices[2].X *= width;
                // vertices 0 and 2 have Z=1, scale by height
                quadVertices[0].Z *= height;
                quadVertices[2].Z *= height;
                break;
            case DIRECTION.DOWN:
                // DOWN face vertices: (1,0,0), (0,0,1), (1,0,1), (0,0,0)
                // scales in X and Z directions
                // vertices 0 and 2 have X=1, scale by width
                quadVertices[0].X *= width;
                quadVertices[2].X *= width;
                // vertices 1 and 2 have Z=1, scale by height
                quadVertices[1].Z *= height;
                quadVertices[2].Z *= height;
                break;
            case DIRECTION.BACK:
                // BACK face vertices: (0,0,1), (1,1,1), (1,0,1), (0,1,1)
                // scales in X and Y directions
                // vertices 1 and 2 have X=1, scale by width
                quadVertices[1].X *= width;
                quadVertices[2].X *= width;
                // vertices 1 and 3 have Y=1, scale by height
                quadVertices[1].Y *= height;
                quadVertices[3].Y *= height;
                break;
            case DIRECTION.FORWARD:
                // FORWARD face vertices: (0,0,0), (1,1,0), (0,1,0), (1,0,0)
                // scales in X and Y directions
                // vertices 1 and 3 have X=1, scale by width
                quadVertices[1].X *= width;
                quadVertices[3].X *= width;
                // vertices 1 and 2 have Y=1, scale by height
                quadVertices[1].Y *= height;
                quadVertices[2].Y *= height;
                break;
            case DIRECTION.RIGHT:
                // RIGHT face vertices: (1,1,0), (1,0,1), (1,1,1), (1,0,0)
                // scales in Y and Z directions
                // vertices 0 and 2 have Y=1, scale by width
                quadVertices[0].Y *= width;
                quadVertices[2].Y *= width;
                // vertices 1 and 2 have Z=1, scale by height
                quadVertices[1].Z *= height;
                quadVertices[2].Z *= height;
                break;
            case DIRECTION.LEFT:
                // LEFT face vertices: (0,1,1), (0,0,0), (0,1,0), (0,0,1)
                // scales in Y and Z directions
                // vertices 0 and 2 have Y=1, scale by width
                quadVertices[0].Y *= width;
                quadVertices[2].Y *= width;
                // vertices 0 and 3 have Z=1, scale by height
                quadVertices[0].Z *= height;
                quadVertices[3].Z *= height;
                break;
        }

        return quadVertices;
    }
    
    /**
     * Determines whether specified face of given voxel should have geometry.
     * Water voxels are skipped and processed in different mesher.
     * Non-air voxels render faces only at transitions with air or water voxels.
     * At higher lods foliage voxels are considered to be air.
     * Includes handling of situations when neighbor voxels are in a different column and other.
     */
    private bool ShouldRenderFace(VoxelType currentType, ChunkColumn column, int x, int y, int z, DIRECTION direction, byte voxelStep, int chunkX, int chunkZ)
    {
        // do not render faces for water or air blocks
        if (currentType is VoxelType.WATER or VoxelType.AIR)
        {
            return false;
        }
        
        Vector3Sys directionVector = GetDirectionVector(direction);
        int nx = x + (int)directionVector.X * voxelStep;
        int ny = y + (int)directionVector.Y * voxelStep;
        int nz = z + (int)directionVector.Z * voxelStep;
        
        // render faces pointing up above world height limit
        if (direction == DIRECTION.UP && ny >= column.totalVoxelsY)
        {
            return true;
        }
        
        // do not render faces pointing down below y=0
        if (direction == DIRECTION.DOWN && ny < 0)
        {
            return false;
        }

        // check if chunk boundary is crossed
        int neighborChunkX = nx >= 0 ? nx / chunkVoxelSize : (nx - chunkVoxelSize + 1) / chunkVoxelSize;
        int neighborChunkZ = nz >= 0 ? nz / chunkVoxelSize : (nz - chunkVoxelSize + 1) / chunkVoxelSize;
        
        // do not render vegetation voxels (plants and colors for flowers) at LOD levels > 0
        if (voxelStep > 1 && currentType is VoxelType.PLANT or VoxelType.PLANT_DARK or VoxelType.RED or VoxelType.YELLOW or VoxelType.BLUE or VoxelType.WHITE or VoxelType.BROWN
                or VoxelType.PLANT_WATER or VoxelType.PLANT_DARK_WATER or VoxelType.YELLOW_WATER or VoxelType.BROWN_WATER or VoxelType.RED_WATER or VoxelType.BLUE_WATER or VoxelType.WHITE_WATER)
        {
            return false;
        }

        // check for cross-column boundary (different X or Z chunk)
        bool crossingColumnBoundary = (neighborChunkX != chunkX || neighborChunkZ != chunkZ);

        VoxelType neighborType;
        
        if (crossingColumnBoundary)
        {
            // crossing into a different chunk column, check neighbor
            ORIENTATION neighborOrientation = GetOrientationFromDirection(direction, neighborChunkX - chunkX, neighborChunkZ - chunkZ);
            ChunkColumn neighborColumn = column.GetNeighbor(neighborOrientation);
            // get neighbor voxel type
            if (neighborColumn == null)
            {
                // no neighbor column - treat as air
                neighborType = VoxelType.AIR;
            }
            else
            {
                neighborType = neighborColumn.GetVoxel(nx, (uint)ny, nz, voxelStep);
                
                // at higher LOD levels, check if the volume contains air or if the neighbor is foliage
                if (voxelStep > 1)
                {
                    if (neighborColumn.VolumeContainsAir(nx, (uint)ny, nz, voxelStep))
                    {
                        neighborType = VoxelType.AIR;
                    }
                    // also treat foliage as air at higher LOD levels
                    else if (neighborType is VoxelType.PLANT or VoxelType.PLANT_DARK or VoxelType.RED or VoxelType.YELLOW or VoxelType.BLUE or VoxelType.WHITE or VoxelType.BROWN
                             or VoxelType.PLANT_WATER or VoxelType.PLANT_DARK_WATER or VoxelType.YELLOW_WATER or VoxelType.BROWN_WATER or VoxelType.RED_WATER or VoxelType.BLUE_WATER or VoxelType.WHITE_WATER)
                    {
                        neighborType = VoxelType.AIR;
                    }
                }
            }
        }
        else
        {
            // get neighbor voxel type from same column
            neighborType = column.GetVoxel(nx, (uint)ny, nz, voxelStep);
        }

        // skip plants at higher LOD levels, render faces that face them
        if (voxelStep > 1 && neighborType is VoxelType.PLANT or VoxelType.PLANT_DARK or VoxelType.RED or VoxelType.YELLOW or VoxelType.BLUE or VoxelType.WHITE or VoxelType.BROWN
                or VoxelType.PLANT_WATER or VoxelType.PLANT_DARK_WATER or VoxelType.YELLOW_WATER or VoxelType.BROWN_WATER or VoxelType.RED_WATER or VoxelType.BLUE_WATER or VoxelType.WHITE_WATER)
        {
            return true;
        }
        
        // non-air blocks render faces when facing air or water
        return neighborType is VoxelType.AIR or VoxelType.WATER;
    }
    
    /**
     * Returns size of voxel step in the voxel structure for given lod level.
     */
    private static byte GetVoxelStepForLod(LodLevel lodLevel)
    {
        return lodLevel switch
        {
            LodLevel.LOD0 => 1,
            LodLevel.LOD1 => 4,
            LodLevel.LOD2 => 8,
            _ => 1
        };
    }

    /**
     * Maps DIRECTION to ORIENTATION enum. Needed for quick access to neighbor columns.
     */
    private static ORIENTATION GetOrientationFromDirection(DIRECTION direction, int deltaX, int deltaZ)
    {
        return direction switch
        {
            DIRECTION.FORWARD when deltaZ == -1 && deltaX == 0 => ORIENTATION.SOUTH,    // -Z
            DIRECTION.BACK when deltaZ == 1 && deltaX == 0 => ORIENTATION.NORTH,        // +Z
            DIRECTION.RIGHT when deltaX == 1 && deltaZ == 0 => ORIENTATION.EAST,        // +X
            DIRECTION.LEFT when deltaX == -1 && deltaZ == 0 => ORIENTATION.WEST,        // -X
            _ => ORIENTATION.NORTH // default (should not happen)
        };
    }

    /**
     * Returns direction vector for specified DIRECTION in .net Vector3.
     * Possible runtime optimizations due to vectorization of the operations.
     */
    private static Vector3Sys GetDirectionVector(DIRECTION direction)
    {
        return direction switch
        {
            DIRECTION.UP => new Vector3Sys(0,1,0),
            DIRECTION.DOWN => new Vector3Sys(0,-1,0),
            DIRECTION.BACK => new Vector3Sys(0,0,1),
            DIRECTION.FORWARD => new Vector3Sys(0,0,-1),
            DIRECTION.RIGHT => new Vector3Sys(1,0,0),
            DIRECTION.LEFT => new Vector3Sys(-1,0,0),
            _ => new Vector3Sys(0,1,0) // should never happen
        };
    }

    /**
     * Returns direction vector for specified DIRECTION in godot Vector3.
     * Godot Vector3 format necessary when passing data to engine later on.
     */
    private static Vector3 GetDirectionVectorGodot(DIRECTION direction)
    {
        return direction switch
        {
            DIRECTION.UP => Vector3.Up,
            DIRECTION.DOWN => Vector3.Down,
            DIRECTION.BACK => Vector3.Back,
            DIRECTION.FORWARD => Vector3.Forward,
            DIRECTION.RIGHT => Vector3.Right,
            DIRECTION.LEFT => Vector3.Left,
            _ => Vector3.Up // should never happen
        };
    }
}
