// FILE: Root.cs
// AUTHOR: Otakar Kočí <xkocio00@stud.fit.vut.cz>
// DATE: 2025 - 2026
// NOTE: This file is part of my Bachelor's thesis: Procedural generator of 3D voxel maps
// DESC: Root script of the voxel demo project. Manages and controls everything. Processes UI requests for changes
//			and most importantly manages the overall dynamic and parallel hierarchical world generation and display system.
//			This includes recalculation of active regions and columns of the world on all levels including lod changes based
//			on current player/camera position in the world which triggers generation/update/unload tasks that control
//			all components of the hierarchical system (World/Voxel/Geometry/WorldDisplay - services)

/*
WORLD GENERATION - DISPLAY SYSTEM
- World divided into chunked areas on multiple levels
	- large regions that mostly contain simple 2D representations of the generated world
	- columns of symmetrical vertically stacked chunks
		- for voxel representation of the generated world, allowing user editing, underground
		- for geometry that is generated from voxels
		- for storing edited voxel data to disk
- Root manages which of these regions and columns of chunks should be currently loaded or displayed
	- uses current player/camera position around which centered rectangular regions are computed for each level
	of the hierarchical system based on configured distances
	- these rectangular areas are mapped to 2D grid of regions and columns
	- differences from the previous state to the new mapping result in creation of tasks for each level
	of the hierarchical system - generate, update, unload and display tasks
- these tasks are then processed by services at their level in the system. Tasks at higher levels are waiting
for their dependencies at lower ones (ex. voxelization of a column waits until the region in which it belongs
is generated by the lower level)
- user voxel editing works partially independently on the main scheduling system. Directly causing update tasks
on geometry level that trigger re-display of given chunks at world display level. Voxel edit operation are also
stored to disk by storage service.
- voxel storage stores all voxelized columns and is managed by root itself, generators only fill or use its structures

GENERATION AND DISPLAY HIERARCHY (bottom-up)
WorldDisplayService uses ChunkColumnGeometry
|	- applies geometry to the engine for display
|
GeometryGeneratorService uses GeometryGenerator, internal data in ChunkColumnGeometry structures
|	- generates geometry for voxel representation on column basis
|
VoxelGeneratorService uses VoxelGenerator internal data in ChunkColumns of VoxelStorage
|	- voxelizes region representation into voxel representation on column basis
|
WorldGeneratorService uses WorldGenerator and internal data are in WorldRegions
	- large regions of world parameters - generated height map, placements of features, water, etc.

EDITING HIERARCHY (bottom-up)
WorldDisplayService replaces affected chunks with new geometry
|
GeometryGeneratorService regenerates geometry for affected chunks, triggers re-display, enables voxel editing
|
VoxelEditService raycasts to voxel storage and edits the voxels, triggers chunk geometry regeneration
|	-> StorageService saves resulting voxel operations
Root catches editing events triggers raycast in VoxelEditService, disables voxel editing, until it is finished
*/


using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Godot;

namespace PCGVoxelLandscapes.Scripts;

/**
 * Represents possible display render modes.
 */
public enum DisplayMode : byte
{
	DEFAULT,
	WIREFRAME
}

/**
 * Lod levels supported by all parts of the system.
 */
public enum LodLevel : byte
{
	LOD0, // full quality - each voxel has a cube
	LOD1, // lower quality, used for collisions
	LOD2, // very low quality
	UNLOADED // not rendered, no geometry
}

/**
 * Root of the project. Manages everything.
 * Processes UI requests, starts up world generation, controls world unloading and application shutting down.
 * Manages the dynamic and parallel hierarchical world generation and display system.
 * This includes recalculation of active regions and columns of the world on all levels including lod changes based
 * on current player/camera position in the world which triggers generation/update/unload tasks that control
 * all components of the hierarchical system (World/Voxel/Geometry/WorldDisplay - services).
 * Also handles other aspects such as trigger user voxel edits, origin shifting, moving the sun, etc.
 */
public partial class Root : Node3D
{
	private int seed; // updated by world configuration
	// main world and voxel configuration
	private const int voxelsPerMeter = 16; // in each axis
	private const int terrainUnitsPerMeter = 4; // lower resolution for terrain generation
	private const int metersPerChunk = 4; // chunk size in meters
	private byte chunkCountY; // overall height of the world in voxel chunks
	private byte terrainChunkCountY; // maximal chunk height for terrain, the rest is spacing for features
	private const byte chunkCountYExtraSpacing = 6; // spacing
	private const int metersPerRegion = 256; // size of a world region in meters
	private uint totalVoxelsY; // count of voxels in vertical space
	private uint chunkVoxelSize; // voxel count in one axis of a chunk
	
	// storage
	private VoxelStorage voxelStorage;
	
	private CaveGenerationHelper caveGenerationHelper;
	// current display mode
	private DisplayMode displayMode = DisplayMode.DEFAULT;

	// iterative generation system configuration
	// LOD system configuration, maximal distance of given lod level
	private int lodDistance0 = 10;
	private int lodDistance1 = 40;
	private int lodDistance2 = 80;
	// margins and distance additions for related voxelization and region generation distances
	private int lodDistanceMax;
	private const int lodUnloadMargin = 5;
	private const int regionTerrainMin = 320;
	private const int regionFeaturesMin = 160;
	private const int regionUnloadMargin = 80;
	private const int columnPreparationDistanceAddition = 25;
	private const int columnVoxelizationDistanceAddition = 15;
	private const int columnMeshingDistanceAddition = 5;
	// total number of lods
	private const int lodCount = 3;
	// maximum count of display column applications per frame
	const int maxProcessPerFrame = 2;
	
	// distances for region, voxel and geometry generation and unloading
	private int regionTerrainTriggerDistance; // distance where regions need to have generated terrain
	private int regionFeaturesTriggerDistance; // distance where regions need to be fully generated
	private int columnPreparationDistance; // distance for columns to be readied in voxel storage
	private int columnVoxelizationDistance; // distance for columns to be voxelized
	private int columnMeshingDistance; // distance for columns that need to have generated geometry

	private int regionTriggerDistanceUnload; // regions beyond this distance need to be unloaded
	private int columnDistanceUnload; // columns beyond this distance need to be unloaded at the voxel level
	private int columnMeshingDistanceUnload; // columns beyond this distance need to be unloaded at the geometry level
	// collections for tracking currently active / loaded regions and columns on all levels
	private HashSet<(int x, int z)> loadedRegions;
	private HashSet<(int x, int z)> generatedRegions;
	private HashSet<(int x, int z)> loadedColumns;
	private HashSet<(int x, int z)> generatedColumns;
	private HashSet<(int x, int z)> meshedColumns;
	private Dictionary<(int x, int z), LodLevel> columnLods;

	private const double lodUpdateInterval = 0.5; // update LOD every 0.5 seconds
	private double lastLodUpdateTime;

	// godot scene nodes
	private Player player;
	private Vector3 lastCameraChunkPos = Vector3.Zero;
	private Menu menu;
	private Node3D voxelWorld;
	private Label fpsLabel;
	private Texture2D textureAtlas;
	private DirectionalLight3D sun;
	
	// service instances
	private ModelService modelService;
	private WorldGeneratorService worldGeneratorService;
	private VoxelGeneratorService voxelGeneratorService;
	private GeometryGeneratorService geometryGeneratorService;
	private WorldDisplayService worldDisplayService;
	private StorageService storageService;
	private VoxelEditService voxelEditService;
	
	// sun movement simulation
	private bool sunMovementEnabled;
	private float sunAngle = Mathf.DegToRad(45); // current angle 0 - 2 PI
	private float fadeRad = Mathf.DegToRad(30); // angle range for sunrise / sunset fading
	private const float sunCycleSpeed = 0.1f; // sun rotation speed
	private const float sunOrbitRadius = 200.0f; // distance from player in XZ plane
	private const float sunHeight = 150.0f; // height offset for the sun position

	// state variables
	private bool generatingModels;
	private bool iterativeRuns; // world generation and display runs
	private bool playerNotPlaced;
	private bool waitingForFirstMeshedChunk = true;
	private bool menuOpen;
	private bool allowEditDoneSignal; // whether signalization that editing was processed enables editing, sync with menu
	private bool editingEnabled;
	private bool mouseModeCaptured = true;

	// origin shift offset stuff
	const int originShiftGridCellSize = 512; // cell is X by X meters
	const int originShiftHalfCell = originShiftGridCellSize / 2; // cell center
	private Vector3Int currentOriginShiftOffsetXZ = new(0, 0, 0);
	private volatile bool originShiftPlanned;
	
	// asynchronous task for region - chunk recalculation, needed for control that multiple tasks will not spawn
	private Task calculateRegionsChunksTask;
	// user voxel editing configuration
	private VoxelType editingVoxelType = VoxelType.STONE;
	private byte editingVoxelSize = 1;
	private float maxEditingDistance = 8f;
	
	// world limits for player movement
	private const int worldLimitMetersXMin = -1000000;
	private const int worldLimitMetersXMax = 1000000;
	private const int worldLimitMetersZMin = -1000000;
	private const int worldLimitMetersZMax = 1000000;
	private const int worldLimitMetersYMin = 0;
	private const int worldLimitMetersYMax = 1000;
	
	// precalculated counts of threads based on this system
	private int modelServiceThreads;
	private int worldServiceThreads;
	private int voxelServiceThreads;
	private int geometryServiceThreads;
	
	// generated materials for blocks and water
	private StandardMaterial3D blockMaterialBasic;
	private ShaderMaterial waterMaterial;
	private ShaderMaterial blockMaterialVariance;

	public override void _Ready()
	{
		voxelWorld = GetNode<Node3D>("World");
		fpsLabel = GetNode<Label>("FPSLabel");
		sun = GetNode<DirectionalLight3D>("Sun");
		player = GetNode<Player>("Player");
		menu = GetNode<Menu>("Menu");
		// needed to pass to other components
		WorldEnvironment worldEnvironment = GetNode<WorldEnvironment>("WorldEnvironment");
		
		chunkVoxelSize = voxelsPerMeter * metersPerChunk;
		
		// initialize storage service at predefined directory
		string storagePath = ProjectSettings.GlobalizePath("user://");
		try
		{
			storageService = new StorageService(storagePath);
		}
		catch (Exception ex)
		{
			GD.PrintErr($"Storage service error: {ex.Message}");
			GetTree().Quit();
		}
		// setup menu
		menu.Setup(this, player, worldEnvironment, sun, storageService, worldLimitMetersXMin, worldLimitMetersXMax, worldLimitMetersZMin, worldLimitMetersZMax, editingVoxelType, editingVoxelSize);
		
		// setup player
		player.SetLimits(worldLimitMetersXMin, worldLimitMetersXMax, worldLimitMetersZMin, worldLimitMetersZMax, worldLimitMetersYMin, worldLimitMetersYMax);
		player.SubscribeOnPlayerPositionChanged(OnCameraPositionChanged);

		// generate texture "block" atlas and prepare/load all the materials
		textureAtlas = VoxelAtlas.GenerateTextureAtlas();
		VoxelAtlas.PrecomputeUVs();
		
		blockMaterialBasic = new StandardMaterial3D
		{
			AlbedoTexture = textureAtlas,
			TextureFilter = BaseMaterial3D.TextureFilterEnum.Nearest
		};
		
		waterMaterial = GD.Load<ShaderMaterial>("res://Materials/BlockWaterMaterial.tres");
		
		blockMaterialVariance = GD.Load<ShaderMaterial>("res://Materials/BlockMaterial.tres");
		blockMaterialVariance.SetShaderParameter("atlas_texture", textureAtlas);

		// calculate thread counts on this system
		GD.Print($"Available threads: {System.Environment.ProcessorCount}");
		modelServiceThreads = Math.Max(1, System.Environment.ProcessorCount / 2);
		worldServiceThreads = Math.Max(1, System.Environment.ProcessorCount / 6);
		voxelServiceThreads = Math.Max(1, System.Environment.ProcessorCount / 3);
		geometryServiceThreads = Math.Max(1, (int)(System.Environment.ProcessorCount / 1.3f));
		GD.Print($"Threads assigned - World Generator: {worldServiceThreads}, Voxel Generator: {voxelServiceThreads}, Geometry Service: {geometryServiceThreads}, Model Generator: {modelServiceThreads}");
		
		// switch to title menu, ui control starts
		Input.MouseMode = Input.MouseModeEnum.Visible;
		menu.SwitchToTitleMenu();
	}
	
	/**
	 * Processes information that given region was generated by WorldGeneratorService.
	 * Places player and repositions sun, if it was not yet placed and 0,0 region was currently generated
	 */
	private void OnRegionGenerated(WorldRegion region)
	{
		if (playerNotPlaced && region.posX == 0 && region.posZ == 0)
		{
			// place the player if initial position region was generated
			ushort height = region.GetHeightAtLocalCoords(0, 0);
			Vector3Double playerPosition = new Vector3Double(0, (height / terrainUnitsPerMeter) + 2, 0);
			player.CallDeferred(Player.MethodName.TeleportPlayer, playerPosition.x, playerPosition.y, playerPosition.z);
			playerNotPlaced = false;
			// reposition sun based on initial player position
			CallDeferred(MethodName.MoveSun);
		}
		GD.Print($"World region generated at {region.posX}, {region.posZ}");
	}
	
	/**
	 * Logs successful voxelization of chunk column.
	 */
	private void OnChunkColumnGenerated(ChunkColumn chunkColumn)
	{
		GD.Print($"Chunk column generated at {chunkColumn.chunkX}, {chunkColumn.chunkZ}");
	}
	
	/**
	 * Logs successful generation of column geometry.
	 * If this is the first meshed chunk, then switches UI to in game state.
	 */
	private void OnChunkColumnMeshed(ChunkColumnGeometry chunkColumnGeometry)
	{
		if (waitingForFirstMeshedChunk)
		{
			waitingForFirstMeshedChunk = false;
			menu.CallDeferred(Menu.MethodName.HideCenteredMessage);
			menu.CallDeferred(Menu.MethodName.SwitchToInGame);
		}
		GD.Print($"Chunk column meshed at {chunkColumnGeometry.chunkX}, {chunkColumnGeometry.chunkZ}");
	}

	/**
	 * Distributes generated voxel models of features to world and voxel generators.
	 */
	private void DistributeModelsFromModelGenerator()
	{
		worldGeneratorService.PassModelsToWorldGenerator(new WorldGeneratorModels()
		{
			treeBushModels = modelService.treeBushModels,
			grassModels = modelService.grassModels,
			plantModels =  modelService.plantModels,
			reedModels =  modelService.reedModels,
			waterLilyModels =  modelService.waterLilyModels,
			rockModels =  modelService.rockModels,
			trunkModels =  modelService.trunkModels
		});
		voxelGeneratorService.PassModelsToVoxelGenerator(modelService.stalactiteModels);
	}

	/**
	 * Processes event that voxel model generation was finished.
	 * Distributes the models and starts up iterative world generation.
	 */
	private void OnModelsGenerated()
	{
		generatingModels = false;
		DistributeModelsFromModelGenerator();
		menu.CallDeferred(Menu.MethodName.ShowCenteredMessageLoading, "Generating world ...");
		iterativeRuns = true;
		CallDeferred(MethodName.OnModelsGeneratedMainThreadSync);
	}

	/**
	 * Wrapper for running asynchronous region - chunk calculation with custom struct parameter.
	 * Seems to be necessary for its use in CallDeferred.
	 */
	private void OnModelsGeneratedMainThreadSync()
	{
		CalculateRegionsChunksAsync(player.GetRealPosition());
	}

	/**
	 * Initializes given world, necessary services and generators to startup world generation.
	 * Firstly model generator is run. After it finishes iterative generation starts.
	 */
	public void StartWorldGeneration(WorldSaveConfig worldSaveConfig, bool newGame)
	{
		// process settings to calculate offsets and dependent parameters
		currentOriginShiftOffsetXZ = new Vector3Int(0, 0, 0);
		WorldSettings settings = worldSaveConfig.worldSettings;
		seed = worldSaveConfig.worldSettings.seed;
		terrainChunkCountY = worldSaveConfig.worldSettings.terrainChunkCountY;
		chunkCountY = (byte)(terrainChunkCountY + chunkCountYExtraSpacing);
		totalVoxelsY = (chunkCountY * chunkVoxelSize);
		int maxTerrainHeightInMeters = terrainChunkCountY * metersPerChunk;
		int maxTerrainHeightInTerrainUnits = maxTerrainHeightInMeters * terrainUnitsPerMeter;
		ushort caveStartYLevelTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.cavesStartTerrainHeightRatio);
		ushort explicitWaterLevelTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.explicitWaterLevelTerrainHeightRatio);
		ushort cavesWaterHeightTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.cavesWaterLevelTerrainHeightRatio);
		// init cave gen helper
		CaveGeneratorHelperParams caveGenHelperParams = new CaveGeneratorHelperParams {
			seed = seed,
			thresholdCaves = settings.cavesSpaceAmount,
			thresholdTunnelNodes = settings.cavesTunnelsChance,
			thresholdEntranceNodes = settings.cavesTunnelEntrancesChance,
			caveStartYLevelTerrainUnits = caveStartYLevelTerrainUnits
		};
		caveGenerationHelper = new CaveGenerationHelper(caveGenHelperParams);
		
		if (newGame)
		{
			// player will be placed at 0,0,0 position in new world
			player.TeleportPlayer(new Vector3Double(0, 0, 0));
			playerNotPlaced = true;
		}
		else
		{
			// or last position in loaded worlds
			player.TeleportPlayer(worldSaveConfig.lastPlayerPosition);
			CheckPlanOriginShift();
			MoveSun();
		}
		
		waitingForFirstMeshedChunk = true; // ui switches to game only after first column geometry is generated
		// initialize tracking collections for iterative region - chunk system
		loadedRegions = [];
		generatedRegions = [];
		loadedColumns = [];
		generatedColumns = [];
		meshedColumns = [];
		columnLods = new Dictionary<(int, int), LodLevel>();
		// initialize voxel storage and cave gen helper
		voxelStorage = new VoxelStorage(metersPerChunk, voxelsPerMeter, chunkCountY);
		WorldGeneratorParams worldGenParams = new WorldGeneratorParams // parameters for world generator
		{
			seed = seed,
			maxTerrainHeightInTerrainUnits = maxTerrainHeightInTerrainUnits,
			voxelsPerMeter = voxelsPerMeter,
			metersPerRegion = metersPerRegion,
			metersPerChunk = metersPerChunk,
			unitsPerMeter = terrainUnitsPerMeter,
			cavesStartYLevelTerrainUnits = caveStartYLevelTerrainUnits,
			cavesEnabled = settings.cavesEnabled,
			caveGenerationHelper = caveGenerationHelper,
			lakeSize = LakeSize.FromLakeSizeType(settings.lakeSize),
			waterAvailEffectStrength = WaterAvailEffectStrength.FromWaterAvailEffectStrengthType(settings.waterAvailabilityStrength),
			heightNoiseConfig = HeightNoiseConfig.FromHeightNoiseConfigType(settings.heightNoiseConfig),
			vegetationChance = VegetationChance.FromOverallVegetationChanceType(settings.overallVegetationChance),
			explicitWaterLevelTerrainUnits = explicitWaterLevelTerrainUnits,
			maxRiverLength = settings.maxRiverLength,
			explicitWaterAvailabilityMax = settings.explicitWaterAvailabilityMaxEffect,
			areaAgeThresholds = settings.areaAgeThresholds,
			areaHeightThresholds =  settings.areaHeightThresholds,
			areaWaterAvailabilityThresholds = settings.areaWaterAvailabilityThresholds,
			waterLilyChance = settings.waterLilyChance,
			waterReedsChance = settings.waterReedsChance,
			snowOccurenceThreshold = settings.snowChance
		};
		// initialize world generator service with world generator
		worldGeneratorService = new WorldGeneratorService(worldServiceThreads, worldGenParams);
		VoxelGeneratorParams voxelGenParams = new VoxelGeneratorParams
		{
			voxelStorage =  voxelStorage,
			worldGeneratorService = worldGeneratorService,
			storageService = storageService,
			caveGenerationHelper = caveGenerationHelper,
			seed = seed,
			metersPerRegion = metersPerRegion,
			metersPerChunk = metersPerChunk,
			voxelsPerMeter = voxelsPerMeter,
			terrainUnitsPerMeter = terrainUnitsPerMeter,
			caveStartYLevelTerrainUnits = caveStartYLevelTerrainUnits,
			cavesWaterHeightTerrainUnits = cavesWaterHeightTerrainUnits,
			cavesEnabled = settings.cavesEnabled,
			stalactiteChance = settings.cavesStalactitesChance,
			waterfallChance = settings.cavesWaterfallChance
		};
		// initialize remaining services
		voxelGeneratorService = new VoxelGeneratorService(voxelServiceThreads, voxelGenParams);
		geometryGeneratorService = new GeometryGeneratorService(voxelStorage, voxelGeneratorService, geometryServiceThreads, lodCount, chunkCountY);
		worldDisplayService = new WorldDisplayService(geometryGeneratorService, chunkCountY, waterMaterial, blockMaterialBasic, blockMaterialVariance, voxelWorld);
		voxelEditService = new VoxelEditService(voxelStorage, storageService, worldDisplayService, voxelsPerMeter, chunkCountY, (byte)chunkVoxelSize);
		// and subscribe to their events
		geometryGeneratorService.SubscribeToVoxelEditService(voxelEditService);
		voxelEditService.SubscribeOnEditFailed(OnEditingProcessed);
		worldGeneratorService.SubscribeOnRegionGenerated(OnRegionGenerated);
		voxelGeneratorService.SubscribeOnChunkColumnGenerated(OnChunkColumnGenerated);
		geometryGeneratorService.SubscribeOnColumnGeometryGenerated(OnChunkColumnMeshed);
		geometryGeneratorService.SubscribeOnEditingProcessed(OnEditingProcessed);
		// init, configure and run model generation
		modelService = new ModelService(seed, modelServiceThreads);
		modelService.SubscribeOnModelsGenerated(OnModelsGenerated);
		VoxelModelDefinitions.InsertVoxelModelDefinitions(modelService);
		menu.ShowCenteredMessageLoading($"Generating models ... (0/{modelService.GetTotalModelsCount()})");
		generatingModels = true;
		modelService.GenerateModels();
	}

	/**
	 * Unloads currently active world by disposing of all data instances of services and generators.
	 */
	private void UnloadWorld()
	{
		// need to stop all generation tasks, disable threads, clear storage and services / generators
		iterativeRuns = false;

		voxelEditService = null;
		
		if (worldDisplayService != null)
		{
			worldDisplayService.Dispose();
			worldDisplayService = null;
		}
		
		if (geometryGeneratorService != null)
		{
			geometryGeneratorService.Dispose();
			geometryGeneratorService = null;
		}
		
		if (voxelGeneratorService != null)
		{
			voxelGeneratorService.Dispose();
			voxelGeneratorService = null;
		}
		
		if (worldGeneratorService != null)
		{
			worldGeneratorService.Dispose();
			worldGeneratorService = null;
		}

		caveGenerationHelper = null;
		
		voxelStorage  = null;
		
		if (worldDisplayService != null)
		{
			worldDisplayService.Dispose();
			worldDisplayService = null;
		}

		storageService.Dispose();

		if (modelService != null)
		{
			modelService.Dispose();
			modelService = null;
		}
	
		loadedRegions = null;
		generatedRegions = null;
		loadedColumns = null;
		generatedColumns = null;
		meshedColumns = null;
		columnLods = null;
	}
	
	/**
	 * Configures LOD distances based on supplied values.
	 * For changes of values from UI and loaded application settings.
	 */
	public void SetLodConfiguration(int distance0, int distance1, int distance2)
	{
		lodDistance0 = distance0;
		lodDistance1 = distance1;
		lodDistance2 = distance2;
		
		CalculateRegionChunksDistances(); // needs to recalculate all dependent distances for the iterative system

		// this part does not execute now, as lod can be configured only outside running game
		// I changed this due to remaining issues of the iterative system that resulted in missing columns
		if (iterativeRuns)
		{
			CalculateRegionsChunksAsync(player.GetRealPosition());
		}
	}

	/**
	 * Recalculates distances for the iterative generation system region - chunk calculation step.
	 */
	private void CalculateRegionChunksDistances()
	{
		lodDistanceMax = lodDistance2;
		regionTerrainTriggerDistance = regionTerrainMin + lodDistanceMax;
		regionFeaturesTriggerDistance = regionFeaturesMin + lodDistanceMax;
		columnPreparationDistance = lodDistanceMax + columnPreparationDistanceAddition;
		columnVoxelizationDistance = lodDistanceMax + columnVoxelizationDistanceAddition;
		columnMeshingDistance = lodDistanceMax + columnMeshingDistanceAddition;

		regionTriggerDistanceUnload = regionTerrainTriggerDistance + regionUnloadMargin;
		columnDistanceUnload = columnPreparationDistance + lodUnloadMargin;
		columnMeshingDistanceUnload = columnMeshingDistance + lodUnloadMargin;
	}

	/**
	 * Starts up asynchronous task that runs CalculateRegionsChunks method.
	 * Only a single task can run at the same time.
	 */
	private void CalculateRegionsChunksAsync(Vector3Double cameraPosition)
	{
		if (calculateRegionsChunksTask != null && !calculateRegionsChunksTask.IsCompleted)
			return;

		calculateRegionsChunksTask = Task.Run(() => CalculateRegionsChunks(cameraPosition));
	}

	/**
	 * Calculates regions and columns that on all levels of the hierarchical system that should be now displayed.
	 * And supplies tasks to all levels of the system to change its state to the new one.
	 */
	private void CalculateRegionsChunks(Vector3Double cameraPosition)
	{
		// regions loading - terrain
		var (camRegionX, camRegionZ) = worldGeneratorService.WorldPosToRegionCoords(cameraPosition.x, cameraPosition.z);
		Vector3Double minPos = cameraPosition - new Vector3Double(regionTerrainTriggerDistance, 0, regionTerrainTriggerDistance);
		Vector3Double maxPos = cameraPosition + new Vector3Double(regionTerrainTriggerDistance, 0, regionTerrainTriggerDistance);
		var (minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		var (maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		// generate tasks if not already present
		for (int regionX = minRegionX; regionX <= maxRegionX; regionX++)
		{
			for (int regionZ = minRegionZ; regionZ <= maxRegionZ; regionZ++)
			{
				if (!loadedRegions.Contains((regionX, regionZ)))
				{
					loadedRegions.Add((regionX, regionZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(regionX - camRegionX) + Math.Abs(regionZ - camRegionZ);
					worldGeneratorService.AddTask(new WorldGenTask(REGION_TASK_TYPE.GENERATE_TERRAIN, regionX, regionZ, priority));
				}
			}
		}
		
		// regions loading - features
		minPos = cameraPosition - new Vector3Double(regionFeaturesTriggerDistance, 0, regionFeaturesTriggerDistance);
		maxPos = cameraPosition + new Vector3Double(regionFeaturesTriggerDistance, 0, regionFeaturesTriggerDistance);
		(minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		(maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		// generate tasks if not already present
		for (int regionX = minRegionX; regionX <= maxRegionX; regionX++)
		{
			for (int regionZ = minRegionZ; regionZ <= maxRegionZ; regionZ++)
			{
				if (!generatedRegions.Contains((regionX, regionZ)))
				{
					generatedRegions.Add((regionX, regionZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(regionX - camRegionX) + Math.Abs(regionZ - camRegionZ);
					worldGeneratorService.AddTask(new WorldGenTask(REGION_TASK_TYPE.GENERATE_FEATURES, regionX, regionZ, priority));
				}
			}
		}
		
		// regions unloading
		minPos = cameraPosition - new Vector3Double(regionTriggerDistanceUnload, 0, regionTriggerDistanceUnload);
		maxPos = cameraPosition + new Vector3Double(regionTriggerDistanceUnload, 0, regionTriggerDistanceUnload);
		(minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		(maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		HashSet<(int x, int z)> regionsToUnload = [];
		// actual region removal happens only on the larger rectangle of loaded regions that only cover the terrain generation phase of regions
		foreach (var (regionX, regionZ) in loadedRegions)
		{
			if (regionX < minRegionX || regionX > maxRegionX || regionZ < minRegionZ || regionZ > maxRegionZ)
			{
				regionsToUnload.Add((regionX, regionZ));
			}
		}
		foreach (var region in regionsToUnload)
		{
			loadedRegions.Remove(region);
			generatedRegions.Remove(region);
			worldGeneratorService.UnloadRegion(region.x, region.z);
		}
		regionsToUnload.Clear();
		
		// chunk columns loading
		minPos = cameraPosition - new Vector3Double(columnPreparationDistance, 0, columnPreparationDistance);
		maxPos = cameraPosition + new Vector3Double(columnPreparationDistance, 0, columnPreparationDistance);
		var (minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		var (maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		// create chunk columns in voxel storage if not present
		for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
		{
			for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
			{
				if (!loadedColumns.Contains((chunkX, chunkZ)))
				{
					loadedColumns.Add((chunkX, chunkZ));
					voxelStorage.CreateChunkColumn(chunkX, chunkZ);
				}
			}
		}
		// chunk columns unloading
		minPos = cameraPosition - new Vector3Double(columnDistanceUnload, 0, columnDistanceUnload);
		maxPos = cameraPosition + new Vector3Double(columnDistanceUnload, 0, columnDistanceUnload);
		(minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		(maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		HashSet<(int x, int z)> columnsToUnload = [];
		// for loaded columns with cleanup of voxel storage
		foreach (var (chunkX, chunkZ) in loadedColumns)
		{
			if (chunkX < minChunkX || chunkX > maxChunkX || chunkZ < minChunkZ || chunkZ > maxChunkZ)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		foreach (var chunk in columnsToUnload)
		{
			loadedColumns.Remove(chunk);
			voxelStorage.RemoveChunkColumn(chunk.x, chunk.z);
			GD.Print($"Unloaded chunk column at {chunk.x}, {chunk.z} from voxel storage");
		}
		// for generated active chunks in voxel generator, needs to be split, otherwise voxel storage would have
		// a set of incorrect canceled tasks and some columns would never be generated
		columnsToUnload.Clear();
		foreach (var (chunkX, chunkZ) in generatedColumns)
		{
			if (chunkX < minChunkX || chunkX > maxChunkX || chunkZ < minChunkZ || chunkZ > maxChunkZ)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		foreach (var chunk in columnsToUnload)
		{
			// remove from generated columns
			generatedColumns.Remove(chunk);
		}
		// voxelization unloading
		voxelGeneratorService.UnloadColumns(columnsToUnload);
		columnsToUnload.Clear();
		
		// voxelization loading
		var (camChunkX, camChunkZ) = voxelStorage.WorldPosToChunkCoords(cameraPosition.x, cameraPosition.z);
		minPos = cameraPosition - new Vector3Double(columnVoxelizationDistance, 0, columnVoxelizationDistance);
		maxPos = cameraPosition + new Vector3Double(columnVoxelizationDistance, 0, columnVoxelizationDistance);
		(minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		(maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		// plan voxelization of not yet voxelized columns
		for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
		{
			for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
			{
				if (!generatedColumns.Contains((chunkX, chunkZ)))
				{
					generatedColumns.Add((chunkX, chunkZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(chunkX - camChunkX) + Math.Abs(chunkZ - camChunkZ);
					voxelGeneratorService.AddTask(new ChunkColumnTask(chunkX, chunkZ, priority));
				}
			}
		}
		
		// geometry unloading
		minPos = cameraPosition - new Vector3Double(columnMeshingDistanceUnload, 0, columnMeshingDistanceUnload);
		maxPos = cameraPosition + new Vector3Double(columnMeshingDistanceUnload, 0, columnMeshingDistanceUnload);
		(minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		(maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		foreach (var (chunkX, chunkZ) in meshedColumns)
		{
			if (chunkX < minChunkX || chunkX > maxChunkX || chunkZ < minChunkZ || chunkZ > maxChunkZ)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		
		foreach (var chunk in columnsToUnload)
		{
			meshedColumns.Remove(chunk);
		}
		// unload geometry in one pass
		geometryGeneratorService.UnloadColumns(columnsToUnload);
		columnsToUnload.Clear();
		
		// geometry loading
		minPos = cameraPosition - new Vector3Double(columnMeshingDistance, 0, columnMeshingDistance);
		maxPos = cameraPosition + new Vector3Double(columnMeshingDistance, 0, columnMeshingDistance);
		(minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		(maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		// plan generation of not yet planned geometry
		for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
		{
			for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
			{
				if (!meshedColumns.Contains((chunkX, chunkZ)))
				{
					meshedColumns.Add((chunkX, chunkZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(chunkX - camChunkX) + Math.Abs(chunkZ - camChunkZ);
					geometryGeneratorService.AddNormalTask(new ChunkColumnGeometryTask(GEOMETRY_TASK_TYPE.GENERATE, chunkX, uint.MaxValue, chunkZ, priority));
				}
			}
		}
		
		// calculate target lods for viewing
		Vector3Double minPosLod2 = cameraPosition - new Vector3Double(lodDistance2, 0, lodDistance2);
		Vector3Double maxPosLod2 = cameraPosition + new Vector3Double(lodDistance2, 0, lodDistance2);
		var (minChunkXLod2, minChunkZLod2) = voxelStorage.WorldPosToChunkCoords(minPosLod2.x, minPosLod2.z);
		var (maxChunkXLod2, maxChunkZLod2) = voxelStorage.WorldPosToChunkCoords(maxPosLod2.x, maxPosLod2.z);
		Vector3Double minPosLod1 = cameraPosition - new Vector3Double(lodDistance1, 0, lodDistance1);
		Vector3Double maxPosLod1 = cameraPosition + new Vector3Double(lodDistance1, 0, lodDistance1);
		var (minChunkXLod1, minChunkZLod1) = voxelStorage.WorldPosToChunkCoords(minPosLod1.x, minPosLod1.z);
		var (maxChunkXLod1, maxChunkZLod1) = voxelStorage.WorldPosToChunkCoords(maxPosLod1.x, maxPosLod1.z);
		Vector3Double minPosLod0 = cameraPosition - new Vector3Double(lodDistance0, 0, lodDistance0);
		Vector3Double maxPosLod0 = cameraPosition + new Vector3Double(lodDistance0, 0, lodDistance0);
		var (minChunkXLod0, minChunkZLod0) = voxelStorage.WorldPosToChunkCoords(minPosLod0.x, minPosLod0.z);
		var (maxChunkXLod0, maxChunkZLod0) = voxelStorage.WorldPosToChunkCoords(maxPosLod0.x, maxPosLod0.z);
		// recalculate the lods for chunk columns
		for (int chunkX = minChunkXLod2; chunkX <= maxChunkXLod2; chunkX++)
		{
			for (int chunkZ = minChunkZLod2; chunkZ <= maxChunkZLod2; chunkZ++)
			{
				// switch to correct lod
				LodLevel correctLod = LodLevel.UNLOADED;
				if (chunkX >= minChunkXLod0 && chunkX <= maxChunkXLod0 && chunkZ >= minChunkZLod0 && chunkZ <= maxChunkZLod0)
				{
					correctLod = LodLevel.LOD0;
				}
				else
				if (chunkX >= minChunkXLod1 && chunkX <= maxChunkXLod1 && chunkZ >= minChunkZLod1 && chunkZ <= maxChunkZLod1)
				{
					correctLod = LodLevel.LOD1;
				}
				else 
				if (chunkX >= minChunkXLod2 && chunkX <= maxChunkXLod2 && chunkZ >= minChunkZLod2 && chunkZ <= maxChunkZLod2)
				{
					correctLod = LodLevel.LOD2;
				}

				// new column to display
				if (!columnLods.ContainsKey((chunkX, chunkZ)))
				{
					columnLods[(chunkX, chunkZ)] = correctLod;
					worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.DISPLAY, chunkX, uint.MaxValue, chunkZ, correctLod));
				}
				else
				{ // updating displayed one
					LodLevel currentLod = columnLods[(chunkX, chunkZ)];
					if (currentLod != correctLod)
					{
						columnLods[(chunkX, chunkZ)] = correctLod;
						worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.DISPLAY, chunkX, uint.MaxValue, chunkZ, correctLod));
					}
				}
			}
		}
		
		// displayed columns unloading
		foreach (var (chunkX, chunkZ) in columnLods.Keys)
		{
			if (chunkX < minChunkXLod2 || chunkX > maxChunkXLod2 || chunkZ < minChunkZLod2 || chunkZ > maxChunkZLod2)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		
		foreach (var column in columnsToUnload)
		{
			columnLods.Remove(column);
			worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.HIDE, column.x, uint.MaxValue, column.z, LodLevel.UNLOADED));
		}
	}
	
	/**
	 * Yields current thread to world display service to apply DISPLAY / UPDATE tasks.
	 */
	private void ProcessCompletedMeshes()
	{
		for (int i=0; i < maxProcessPerFrame; i++)
		{
			worldDisplayService.ProcessDisplayUpdateTask();
		}
	}
	
	/**
	 * Fired when player camera changes position.
	 * Repositions sun based on player position, if it is not in automatic sun cycle.
	 * Starts up region - chunk recalculation and check for origin shift process with debouncing.
	 */
	private void OnCameraPositionChanged()
	{
		if (!iterativeRuns)
			return;
		
		// reposition sun based on player position, when automatic sun movement is disabled
		if (!sunMovementEnabled)
		{
			MoveSun();
		}
		
		// this debounce is not as necessary now, when only a single async thread can run the calculation at once
		double currentTime = Time.GetUnixTimeFromSystem();
		if (currentTime - lastLodUpdateTime < lodUpdateInterval)
			return;
		
		lastLodUpdateTime = currentTime;
		Vector3Double playerPosition = player.GetRealPosition();
		CalculateRegionsChunksAsync(playerPosition);
		
		CheckPlanOriginShift();
	}
	
	/**
	 * Performs origin shift change with the precomputed offset vector.
	 */
	private void PerformOriginShift()
	{
		// needs to freeze player, move the world and then unfreeze the player
		player.FreezeBeforeOriginShift();
		worldDisplayService.ApplyOriginShift(currentOriginShiftOffsetXZ);
		player.ApplyOriginShift(currentOriginShiftOffsetXZ);
		player.UnfreezeAfterOriginShift();
	}
	
	/**
	 * Checks whether the origin shift vector should change based on different position of player/camera.
	 * Shifting is done on a centered XZ grid of cells. When player moves across cell borders, a different
	 * shift vector is computed so that the whole world and the player would always be placed around the center
	 * of engine coordinate system to reduce floating point precision errors during rendering and physics.
	 * The cell with offset 0,0 is at -halfCell to halfCell area in both X and Z dimension.
	 */
	private void CheckPlanOriginShift()
	{
		if (originShiftPlanned)
			return;
		
		Vector3Double playerPosition = player.GetRealPosition();

		// calculate current cell coordinates of the player
		int cellX = (int)Math.Floor((playerPosition.x + originShiftHalfCell) / originShiftGridCellSize);
		int cellZ = (int)Math.Floor((playerPosition.z + originShiftHalfCell) / originShiftGridCellSize);

		// new origin offset
		int newOffsetX = - cellX * originShiftGridCellSize;
		int newOffsetZ = - cellZ * originShiftGridCellSize;

		// trigger shift, when cells differ
		if (newOffsetX == currentOriginShiftOffsetXZ.x && newOffsetZ == currentOriginShiftOffsetXZ.z)
			return;

		Vector3Int newOriginShift = new Vector3Int(newOffsetX, 0, newOffsetZ);
		currentOriginShiftOffsetXZ = newOriginShift;
		originShiftPlanned = true;
	}

	/**
	 * Teleports player to specified real (non-shifted) position
	 */
	public void TeleportPlayer(Vector3Double realPosition)
	{
		if (!iterativeRuns)
			return;
		
		// reset to bogus value to always trigger a shift offset recalculation
		currentOriginShiftOffsetXZ = new Vector3Int(int.MaxValue, int.MaxValue, int.MaxValue);
		player.TeleportPlayer(realPosition);
		originShiftPlanned = false;
		CheckPlanOriginShift();
		// necessary to recalculate active regions - chunks
		CalculateRegionsChunksAsync(realPosition);
	}
	
	/**
	 * Triggered when the menu changes state to allow / disallow player voxel editing.
	 */
	public void OnEditingStatusChange(bool enabled, bool signalEnabled)
	{
		editingEnabled = enabled;
		allowEditDoneSignal = signalEnabled;
	}
	
	/**
	 * Periodic engine yielded invocation.
	 * Processes updates to the debug menu, allows toggling of several features (debug menu, wireframe, sun movement).
	 * Triggers voxel editing based on user input and runs the sun movement code.
	 */
	public override void _Process(double delta)
	{
		// show model generation progress
		if (generatingModels)
		{
			uint totalModels = modelService.GetTotalModelsCount();
			uint remainingModels = modelService.GetRemainingTasksCount();
			menu.ShowCenteredMessageLoading($"Generating models... {totalModels - remainingModels}/{totalModels}");
		}

		if (iterativeRuns)
		{
			// update debug menu with stats
			var worldGenActiveRegions = worldGeneratorService.GetActiveRegionsCount();
			var worldGenRemainingTasks = worldGeneratorService.GetRemainingTasksCount();
			var worldGenLockedTasks = worldGeneratorService.GetLockedTasksCount();
			var worldGenWorkingTasks = worldGeneratorService.GetActiveThreadsCount();
			var voxelGenActiveColumns = voxelGeneratorService.GetActiveColumnsCount();
			var voxelGenRemainingTasks = voxelGeneratorService.GetRemainingTasksCount();
			var voxelGenLockedTasks = voxelGeneratorService.GetLockedTasksCount();
			var voxelGenWaitingNeighborsCount = voxelGeneratorService.GetWaitingNeighborsCount();
			var modelGenRemainingTasks = modelService.GetRemainingTasksCount();
			var geometryGenRemainingTasks = geometryGeneratorService.GetRemainingTasksCount();
			var geometryGenLockedTasks = geometryGeneratorService.GetLockedTasksCount();
			var geometryGenActiveColumns = geometryGeneratorService.GetActiveColumnsCount();
			var geometryGenAverageChunkLODTime = geometryGeneratorService.GetAverageChunkLodGenerationTime();
			var meshViewDisplayedColumns = worldDisplayService.GetDisplayedColumnsCount();
			var meshViewRemainingTasks = worldDisplayService.GetRemainingTasksCount();
			var meshViewLockedTasks = worldDisplayService.GetLockedTasksCount();
			Vector3Double realPlayerPosition = player.GetRealPosition();
			var cameraChunk = new Vector3Int(
				(int)Math.Floor(realPlayerPosition.x / metersPerChunk),
				(int)Math.Floor(realPlayerPosition.y / metersPerChunk),
				(int)Math.Floor(realPlayerPosition.z / metersPerChunk)
			);
			Vector3 shiftedPlayerPosition = player.Position;

			fpsLabel.Text = $"WORLD GEN (A/W/R/L): {worldGenActiveRegions}/{worldGenWorkingTasks}/{worldGenRemainingTasks}/{worldGenLockedTasks}\n" +
							$"VOXEL GEN (A/R/L): {voxelGenActiveColumns}/{voxelGenRemainingTasks}/{voxelGenLockedTasks}/{voxelGenWaitingNeighborsCount}\n" +
							$"GEOMT GEN (A/R/L): {geometryGenActiveColumns}/{geometryGenRemainingTasks}/{geometryGenLockedTasks}\n" +
							$"MESH  GEN: {geometryGenAverageChunkLODTime} ms average\n" +
							$"MESH VIEW (A/R/L): {meshViewDisplayedColumns}/{meshViewRemainingTasks}/{meshViewLockedTasks}\n" +
							$"MODEL GEN (R): {modelGenRemainingTasks}\n" +
							$"CAMERA CHUNK: {cameraChunk.x}, {cameraChunk.y}, {cameraChunk.z}\n" +
							$"CAMERA POSITION: {Math.Round(realPlayerPosition.x, 2)}, {Math.Round(realPlayerPosition.y, 2)}, {Math.Round(realPlayerPosition.z, 2)}\n" +
							$"ORIGIN SHIFT OFFSET: {currentOriginShiftOffsetXZ.x}, {currentOriginShiftOffsetXZ.z}\n" +
							$"SHIFTED CAMERA POSITION: {Math.Round(shiftedPlayerPosition.X, 2)}, {Math.Round(shiftedPlayerPosition.Y, 2)}, {Math.Round(shiftedPlayerPosition.Z, 2)}";

		}
		// toggle debug menu
		if (Input.IsActionJustPressed("debug_menu"))
		{
			fpsLabel.SetVisible(!fpsLabel.Visible);
		}
		// toggle wireframe display
		if (Input.IsActionJustPressed("toggle_wireframe"))
		{
			switch (displayMode)
			{
				case DisplayMode.DEFAULT:
					GetViewport().DebugDraw = Viewport.DebugDrawEnum.Wireframe;
					displayMode = DisplayMode.WIREFRAME;
					break;
				case DisplayMode.WIREFRAME:
					GetViewport().DebugDraw = Viewport.DebugDrawEnum.Disabled;
					displayMode = DisplayMode.DEFAULT;
					break;
			}
		}
		
		// block placement and removal
		if (editingEnabled)
		{
			if (Input.IsActionJustReleased("destroy_block"))
			{
				Vector3 lookAtDirection = player.GetLookAtDirection();
				Vector3Double playerPosition = player.GetCenteredCameraRealPosition();
				
				// block destruction - async
				editingEnabled = false;
				voxelEditService.RaycastVoxelEditAsync(playerPosition, lookAtDirection, maxEditingDistance, editingVoxelType, editingVoxelSize, false);
			}
			else if (Input.IsActionJustReleased("place_block"))
			{
				Vector3 lookAtDirection = player.GetLookAtDirection();
				Vector3Double playerPosition = player.GetCenteredCameraRealPosition();
				
				// block placement - async
				editingEnabled = false;
				voxelEditService.RaycastVoxelEditAsync(playerPosition, lookAtDirection, maxEditingDistance, editingVoxelType, editingVoxelSize, true);
			}
		}
		// toggle sun automatic cycle
		if (Input.IsActionJustPressed("toggle_sun"))
		{
			sunMovementEnabled = !sunMovementEnabled;
		}
		
		// update sun position if automatic sun cycle is enabled
		if (sunMovementEnabled)
		{
			UpdateSunPosition(delta);
		}
	}

	/**
	 * Resets state of the app when starting new world
	 */
	public void ResetWorldPlayerSettings()
	{
		sunMovementEnabled = false;
		GetViewport().DebugDraw = Viewport.DebugDrawEnum.Disabled;
		displayMode = DisplayMode.DEFAULT;
	}
	
	/**
	 * Toggles mouse capture mode.
	 * In game vs menus.
	 */
	private void ToggleMouseCaptureMode()
	{
		mouseModeCaptured = !mouseModeCaptured;
		if (mouseModeCaptured)
		{
			Input.MouseMode = Input.MouseModeEnum.Captured;
		}
		else
		{
			Input.MouseMode = Input.MouseModeEnum.Visible;
		}
	}
	
	/**
	 * Periodic engine yielded invocation.
	 * Yields itself to the world display service to process its tasks.
	 * Runs cleanup of displayed columns that are to be removed.
	 * And performs planned origin shift update.
	 */
	public override void _PhysicsProcess(double delta)
	{
		if (!iterativeRuns)
			return;
		
		// hide columns
		worldDisplayService.ProcessPlannedMeshUnloads();
		// process column display and updates
		ProcessCompletedMeshes();
		// perform origin shift when planned
		if (originShiftPlanned)
		{
			PerformOriginShift();
			originShiftPlanned = false;
		}
	}
	
	/**
	 * Signalizes that processing of last user voxel edit has finished.
	 * Re-enables editing if allowed.
	 */
	private void OnEditingProcessed()
	{
		if (allowEditDoneSignal)
		{
			editingEnabled = true;
		}
	}

	/**
	 * Moves sun to a new position based on current player position and sun angle
	 * of rotation around the world.
	 * If automatic sun cycle is not enabled, this only repositions the sun to correctly move
	 * with the player through the world.
	 */
	private void MoveSun()
	{
		// get player position
		Vector3 playerPos = player.GlobalPosition;
		
		// calculate sun position in circle around player
		// sun moves in a vertical circle perpendicular to the ground
		float sunX = playerPos.X + Mathf.Cos(sunAngle) * sunOrbitRadius;
		float sunY = playerPos.Y + Mathf.Sin(sunAngle) * sunOrbitRadius + sunHeight;
		float sunZ = playerPos.Z;
		
		Vector3 sunPosition = new Vector3(sunX, sunY, sunZ);
		sun.GlobalPosition = sunPosition;
		
		// sun looks toward player position
		sun.LookAt(playerPos, Vector3.Up);
	}
	
	/**
	 * Advances the sun angle around the world (player)
	 * Updates its energy based on the angle:
	 * Sun increases energy as it goes up 0 - fadeRad,
	 * then stays at full energy until it reaches pi - fadeRad,
	 * when it starts to reduce its energy as it goes down.
	 * Its energy is zero when it is below the horizon.
	 * The angle is then applied in MoveSun method.
	 */
	private void UpdateSunPosition(double delta)
	{
		// increment the angle based on time and speed
		sunAngle += sunCycleSpeed * (float)delta;
		
		// keep angle in 0 to 2 PI range
		if (sunAngle >= Mathf.Tau)
		{
			sunAngle -= Mathf.Tau;
		}
		
		// move sun to new position based on player position and updated angle
		MoveSun();
		
		// update sun energy
		float sunEnergy;
		
		// upper half, sun is above the horizon
		if (sunAngle <= Mathf.Pi)
		{
			// 0 - fadeRad, sun rising
			if (sunAngle < fadeRad)
			{
				// fade energy in
				sunEnergy = sunAngle / fadeRad;
			}
			// (PI - fadeRad) - PI, sun going down
			else if (sunAngle > Mathf.Pi - fadeRad)
			{
				// fade energy out
				sunEnergy = (Mathf.Pi - sunAngle) / fadeRad;
			}
			// middle, full brightness
			else
			{
				sunEnergy = 1.0f;
			}
		}
		// lower half, sun below the horizon, dimmed
		else
		{
			sunEnergy = 0.0f;
		}
		
		sun.LightEnergy = sunEnergy;
	}

	/**
	 * Changing voxel type for editing.
	 */
	public void OnVoxelEditTypeChanged(int index)
	{
		editingVoxelType = (VoxelType)index;
	}
	
	/**
	 * Changing editing voxel size.
	 */
	public void OnVoxelEditSizeChanged(float value)
	{
		editingVoxelSize = (byte)Math.Pow(2, (int)(value - 1));
	}
	
	//NOTE: In both world exit cases it is the menu code that triggers world config save with last player position.

	/**
	 * Unloads current world as it leaves game for title menu.
	 */
	public void OnExitToTitleMenu()
	{
		UnloadWorld();
	}

	/**
	 * Unloads current world and quits.
	 */
	public void OnExit()
	{
		UnloadWorld();
		GetTree().Quit();
	}
}
