// FILE: Root.cs
// AUTHOR: Otakar Kočí <xkocio00@stud.fit.vut.cz>
// DATE: 2025 - 2026
// NOTE: This file is part of my Bachelor's thesis: Procedural generator of 3D voxel maps
// DESC: Root script of the voxel demo project. Manages and controls everything. Processes UI requests for changes
//			and most importantly manages the overall dynamic and parallel hierarchical world generation and display system.
//			This includes recalculation of active regions and columns of the world on all levels including lod changes based
//			on current player/camera position in the world which triggers generation/update/unload tasks that control
//			all components of the hierarchical system (World/Voxel/Geometry/WorldDisplay - services)

/*
WORLD GENERATION - DISPLAY SYSTEM
- World divided into chunked areas on multiple levels
	- large regions that mostly contain simple 2D representations of the generated world
	- columns of symmetrical vertically stacked chunks
		- for voxel representation of the generated world, allowing user editing, underground
		- for geometry that is generated from voxels
		- for storing edited voxel data to disk
- Root manages which of these regions and columns of chunks should be currently loaded or displayed
	- uses current player/camera position around which centered circular areas are computed for each level
	of the hierarchical system based on configured distances
	- these circular areas are mapped to a 2D grid of regions and columns
	- differences from the previous state to the new mapping result in creation of tasks for each level
	of the hierarchical system - generate, update, unload and display tasks
- these tasks are then processed by services at their level in the system. Tasks at higher levels are waiting
for their dependencies at lower ones (ex. voxelization of a column waits until the region in which it belongs
is generated by the lower level)
- user voxel editing works partially independently on the main scheduling system. Directly causing update tasks
on geometry level that trigger re-display of given chunks at world display level. Voxel edit operations are also
stored to disk by storage service.
- voxel storage stores all voxelized columns and is managed by root itself, generators and services only fill or use its structures

GENERATION AND DISPLAY HIERARCHY (bottom-up)
WorldDisplayService uses ChunkColumnGeometry
|	- applies geometry to the engine for display
|
GeometryGeneratorService uses GeometryGenerator, internal data in ChunkColumnGeometry structures
|	- generates geometry for voxel representation on column basis
|
VoxelGeneratorService uses VoxelGenerator internal data in ChunkColumns of VoxelStorage
|	- voxelizes region representation into voxel representation on column basis
|
WorldGeneratorService uses WorldGenerator and internal data are in WorldRegions
	- large regions of world parameters - generated height map, placements of features, water, etc.

EDITING HIERARCHY (bottom-up)
WorldDisplayService replaces affected chunks with new geometry
|
GeometryGeneratorService regenerates geometry for affected chunks, triggers re-display, enables voxel editing
|
VoxelEditService raycasts to voxel storage and edits the voxels, triggers chunk geometry regeneration
|	-> StorageService saves resulting voxel operations
Root catches editing events, triggers raycast in VoxelEditService, disables voxel editing, until it is finished
*/


using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Godot;

namespace PCGVoxelLandscapes.Scripts;

/**
 * Represents possible display render modes.
 */
public enum DisplayMode : byte
{
	DEFAULT,
	WIREFRAME
}

/**
 * Lod levels supported by all parts of the system.
 */
public enum LodLevel : byte
{
	LOD0, // full quality - each voxel has a cube
	LOD1, // medium quality, used for collisions
	LOD2, // low quality
    LOD3, // very low quality
	UNLOADED // not rendered, no geometry
}

/**
 * Root of the project. Manages everything.
 * Processes UI requests, starts up world generation, controls world unloading and application shutdown.
 * Manages the dynamic and parallel hierarchical world generation and display system.
 * This includes recalculation of active regions and columns of the world on all levels including lod changes based
 * on current player/camera position in the world which triggers generation/update/unload tasks that control
 * all components of the hierarchical system (World/Voxel/Geometry/WorldDisplay - services).
 * Also handles other aspects such as trigger user voxel edits, origin shifting, moving the sun, etc.
 */
public partial class Root : Node3D
{
	private int seed; // updated by world configuration
	// main world and voxel configuration
	private const int voxelsPerMeter = 16; // in each axis
	private const int terrainUnitsPerMeter = 4; // lower resolution for terrain generation
	private const int metersPerChunk = 4; // chunk size in meters
	private byte chunkCountY; // overall height of the world in voxel chunks
	private byte terrainChunkCountY; // maximal chunk height for terrain, the rest is spacing for features
	private const byte chunkCountYExtraSpacing = 6; // spacing
	private const int metersPerRegion = 256; // size of a world region in meters
	private uint totalVoxelsY; // count of voxels in vertical space
	private uint chunkVoxelSize; // voxel count in one axis of a chunk
	
	// storage
	private VoxelStorage voxelStorage;
	
	private CaveGenerationHelper caveGenerationHelper;
	// current display mode
	private DisplayMode displayMode = DisplayMode.DEFAULT;

	// iterative generation system configuration
	// LOD system configuration, maximal distance of given lod level
	private int[] lodDistances = new int[lodCount] {10, 30, 50, 90};
	private int[] lodDistSquared = new int[lodCount];
    
	// margins and distance additions for related voxelization and region generation distances
	private int lodDistanceMax;
	private const int columnStorageUnloadMargin = 10; // distance margin after which columns are unloaded from voxel storage
    private const int columnGeneratorCancelMargin = 10; // dist margin after which column voxelization tasks are canceled
	private const int regionTerrainMin = 320;
	private const int regionFeaturesMin = 160;
	private const int regionUnloadMargin = 80;
	private const int columnPreparationDistanceAddition = 25;
	private const int columnVoxelizationDistanceAddition = 15;
	private const int columnMeshingDistanceAddition = 5; // further away higher
    private const int columnGeometryUnloadMargin = 5;
	// total number of lods
	private const int lodCount = 4;
	
	// distances for region, voxel and geometry generation and unloading
	// squared values are for circular chunk system recalculations
	private int regionTerrainTriggerDistance; // distance where regions need to have generated terrain
	private int regionFeaturesTriggerDistance; // distance where regions need to be fully generated
	private int columnPreparationDistance; // distance for columns to be readied in voxel storage
	private int columnPrepDistSquared;
	private int columnVoxelizationDistance; // distance for columns to be voxelized
	private int columnVoxDistSquared; 
	private int[] columnMeshingLodDistances = new int[lodCount]; // meshing distances for lods
	private int[] columnMeshingLodDistSquared = new int[lodCount];

	private int regionTriggerDistanceUnload; // regions beyond this distance need to be unloaded
	private int columnStorageDistanceUnload; // columns beyond this distance need to be unloaded at the voxel level
	private int columnStorageDistUnloadSquared;
    private int columnGeneratorDistCancel; // voxelization tasks (columns) are canceled beyond this distance
    private int columnGeneratorDistCancelSquared;
	private int[] columnMeshingLodUnloadDistances = new int[lodCount]; // mesh unloading distances for lods
	private int[] columnMeshingLodUnloadDistSquared = new int[lodCount];
    
	// collections for tracking currently active / loaded regions and columns on all levels
	private HashSet<(int x, int z)> loadedRegions;
	private HashSet<(int x, int z)> generatedRegions;
	private HashSet<(int x, int z)> loadedColumns;
	private HashSet<(int x, int z)> generatedColumns;
    private HashSet<(int x, int z)>[] meshedColumnLods = new HashSet<(int x, int z)>[lodCount];
	private Dictionary<(int x, int z), LodLevel> columnLods;

	private const double lodUpdateInterval = 0.5; // update LOD every 0.5 seconds
	private double lastLodUpdateTime;
	private const int chunkUpdatesDeltaDivider = 16; // divider of current frame delta, higher values decrease number of chunk updates per frame

	// godot scene nodes
	private Player player;
	private Vector3 lastCameraChunkPos = Vector3.Zero;
	private Menu menu;
	private Node3D voxelWorld;
	private Label fpsLabel;
	private Texture2D textureAtlas;
	private DirectionalLight3D sun;
    private DirectionalLight3D moon;
	
	// service instances
	private ModelService modelService;
	private WorldGeneratorService worldGeneratorService;
	private VoxelGeneratorService voxelGeneratorService;
	private GeometryGeneratorService geometryGeneratorService;
	private WorldDisplayService worldDisplayService;
	private StorageService storageService;
	private VoxelEditService voxelEditService;
    
    // weather, day-night cycle
    private WeatherEnvironmentManager weatherEnvManager;

	// state variables
	private bool generatingModels;
	private bool iterativeRuns; // world generation and display runs
	private bool playerNotPlaced;
	private bool waitingForFirstMeshedChunk = true;
	private bool menuOpen;
	private bool allowEditDoneSignal; // whether signalization that editing was processed enables editing, sync with menu
	private bool editingEnabled;
	private bool mouseModeCaptured = true;

	// origin shift offset stuff
	const int originShiftGridCellSize = 512; // cell is X by X meters
	const int originShiftHalfCell = originShiftGridCellSize / 2; // cell center
	private Vector3Int currentOriginShiftOffsetXZ = new(0, 0, 0);
	private volatile bool originShiftPlanned;
	
	// asynchronous task for region - chunk recalculation, needed for control that multiple tasks will not spawn
	private Task calculateRegionsChunksTask;
	// user voxel editing configuration
	private VoxelType editingVoxelType = VoxelType.STONE;
	private byte editingVoxelSize = 1;
	private float maxEditingDistance = 8f;
	
	// world limits for player movement
	private const int worldLimitMetersXMin = -1000000;
	private const int worldLimitMetersXMax = 1000000;
	private const int worldLimitMetersZMin = -1000000;
	private const int worldLimitMetersZMax = 1000000;
	private const int worldLimitMetersYMin = 0;
	private const int worldLimitMetersYMax = 1000;
	
	// precalculated counts of threads based on this system
	private int modelServiceThreads;
	private int worldServiceThreads;
	private int voxelServiceThreads;
	private int geometryServiceThreads;
	
	// generated materials for blocks and water
	private StandardMaterial3D blockMaterialBasic;
	private ShaderMaterial waterMaterial;
	private ShaderMaterial blockMaterialVariance;

	public override void _Ready()
	{
		voxelWorld = GetNode<Node3D>("World");
		fpsLabel = GetNode<Label>("FPSLabel");
		sun = GetNode<DirectionalLight3D>("Sun");
        moon = GetNode<DirectionalLight3D>("Moon");
		player = GetNode<Player>("Player");
		menu = GetNode<Menu>("Menu");
		// needed to pass to other components
		WorldEnvironment worldEnvironment = GetNode<WorldEnvironment>("WorldEnvironment");
		
		chunkVoxelSize = voxelsPerMeter * metersPerChunk;

        weatherEnvManager = new WeatherEnvironmentManager(player, sun, moon, worldEnvironment, metersPerRegion, terrainUnitsPerMeter);
		
		// initialize storage service at predefined directory
		string storagePath = ProjectSettings.GlobalizePath("user://");
		try
		{
			storageService = new StorageService(storagePath);
		}
		catch (Exception ex)
		{
			GD.PrintErr($"Storage service error: {ex.Message}");
			GetTree().Quit();
		}
		// setup menu
		menu.Setup(this, player, weatherEnvManager, worldEnvironment, sun, storageService, worldLimitMetersXMin, worldLimitMetersXMax, worldLimitMetersZMin, worldLimitMetersZMax);
		
		// setup player
		player.SetLimits(worldLimitMetersXMin, worldLimitMetersXMax, worldLimitMetersZMin, worldLimitMetersZMax, worldLimitMetersYMin, worldLimitMetersYMax);
		player.SubscribeOnPlayerPositionChanged(OnCameraPositionChanged);

		// generate texture "block" atlas and prepare/load all the materials
		textureAtlas = VoxelAtlas.GetTextureAtlas();
		VoxelAtlas.PrecomputeUVs();
		
		blockMaterialBasic = new StandardMaterial3D
		{
			AlbedoTexture = textureAtlas,
			TextureFilter = BaseMaterial3D.TextureFilterEnum.Nearest
		};
		
		waterMaterial = GD.Load<ShaderMaterial>("res://Materials/BlockWaterMaterial.tres");
		
		blockMaterialVariance = GD.Load<ShaderMaterial>("res://Materials/BlockMaterial.tres");
		blockMaterialVariance.SetShaderParameter("atlas_texture", textureAtlas);

		// calculate thread counts on this system
		GD.Print($"Available threads: {System.Environment.ProcessorCount}");
		modelServiceThreads = Math.Max(1, (int)(System.Environment.ProcessorCount / 1.5f));
		worldServiceThreads = Math.Max(1, System.Environment.ProcessorCount / 3);
		voxelServiceThreads = Math.Max(1, System.Environment.ProcessorCount / 3);
		geometryServiceThreads = Math.Max(1, (int)(System.Environment.ProcessorCount / 1.25f));
		GD.Print($"Threads assigned - World Generator: {worldServiceThreads}, Voxel Generator: {voxelServiceThreads}, Geometry Service: {geometryServiceThreads}, Model Generator: {modelServiceThreads}");
		
		// switch to title menu, ui control starts
		Input.MouseMode = Input.MouseModeEnum.Visible;
		menu.SwitchToTitleMenu();
	}
	
	/**
	 * Processes information that given region was generated by WorldGeneratorService.
	 * Places player and repositions sun, if it was not yet placed and 0,0 region was currently generated
	 */
	private void OnRegionGenerated(WorldRegion region)
	{
		if (playerNotPlaced && region.posX == 0 && region.posZ == 0)
		{
			// place the player if initial position region was generated
			ushort height = region.GetHeightAtLocalCoords(0, 0);
			Vector3Double playerPosition = new Vector3Double(0, (height / terrainUnitsPerMeter) + 2, 0);
			player.CallDeferred(Player.MethodName.TeleportPlayer, playerPosition.x, playerPosition.y, playerPosition.z);
			playerNotPlaced = false;
			// reposition sun based on initial player position
			CallDeferred(MethodName.MoveLightsInWeatherManager);
            // reset player pos in weather manager
            CallDeferred(MethodName.PassPlayerPosChangeToWeatherManager);
        }
		GD.Print($"World region generated at {region.posX}, {region.posZ}");
	}

    /**
     * Dirty way to use call deferred on non-godot class objects.
     * Called from OnRegionGenerated.
     */
    private void PassPlayerPosChangeToWeatherManager()
    {
        weatherEnvManager.OnPlayerPositionChanged();
    }

    /**
     * Dirty way to use call deferred on non-godot class objects.
     * Called from OnRegionGenerated.
     */
    private void MoveLightsInWeatherManager()
    {
        weatherEnvManager.MoveLights();
    }
	
	/**
	 * Logs successful voxelization of chunk column.
	 */
	private void OnChunkColumnGenerated(ChunkColumn chunkColumn)
	{
		GD.Print($"Chunk column generated at {chunkColumn.chunkX}, {chunkColumn.chunkZ}");
	}
	
	/**
	 * Logs successful generation of column geometry.
	 * If this is the first meshed chunk, then switches UI to in game state.
	 */
	private void OnChunkColumnMeshed(ChunkColumnGeometry chunkColumnGeometry)
	{
		if (waitingForFirstMeshedChunk)
		{
			waitingForFirstMeshedChunk = false;
			menu.CallDeferred(Menu.MethodName.HideCenteredMessage);
			menu.CallDeferred(Menu.MethodName.SwitchToInGame, true);
            weatherEnvManager.SetDayCycleStatus(menu.currentWorldSaveConfig.dayCycleEnabled);
            weatherEnvManager.SetWeatherSimulationStatus(menu.currentWorldSaveConfig.weatherSimulationEnabled);
            menu.CallDeferred(Menu.MethodName.UpdateInGameDayCycleState, menu.currentWorldSaveConfig.dayCycleEnabled);
            menu.CallDeferred(Menu.MethodName.UpdateInGameWeatherSimulationState, menu.currentWorldSaveConfig.weatherSimulationEnabled);
        }
		GD.Print($"Chunk column meshed at {chunkColumnGeometry.chunkX}, {chunkColumnGeometry.chunkZ}");
	}

	/**
	 * Distributes generated voxel models of features to world and voxel generators.
	 */
	private void DistributeModelsFromModelGenerator()
	{
		worldGeneratorService.PassModelsToWorldGenerator(new WorldGeneratorModels()
		{
			treeBushModels = modelService.treeBushModels,
			grassModels = modelService.grassModels,
			plantModels =  modelService.plantModels,
            plantBushModels = modelService.plantBushModels,
			reedModels =  modelService.reedModels,
			waterLilyModels =  modelService.waterLilyModels,
			rockModels =  modelService.rockModels,
			trunkModels =  modelService.trunkModels
		});
		voxelGeneratorService.PassModelsToVoxelGenerator(modelService.stalactiteModels);
	}

	/**
	 * Processes event that voxel model generation was finished.
	 * Distributes the models and starts up iterative world generation.
	 */
	private void OnModelsGenerated()
	{
		generatingModels = false;
		DistributeModelsFromModelGenerator();
		menu.CallDeferred(Menu.MethodName.ShowCenteredMessageLoading, "Generating world ...");
		iterativeRuns = true;
		CallDeferred(MethodName.OnModelsGeneratedMainThreadSync);
	}

	/**
	 * Wrapper for running asynchronous region - chunk calculation with custom struct parameter.
	 * Seems to be necessary for its use in CallDeferred.
	 */
	private void OnModelsGeneratedMainThreadSync()
	{
		CalculateRegionsChunksAsync(player.GetRealPosition());
	}

	/**
	 * Initializes given world, necessary services and generators to startup world generation.
	 * Firstly model generator is run. After it finishes iterative generation starts.
	 */
	public void StartWorldGeneration(WorldSaveConfig worldSaveConfig, bool newGame)
	{
		// process settings to calculate offsets and dependent parameters
		currentOriginShiftOffsetXZ = new Vector3Int(0, 0, 0);
		WorldSettings settings = worldSaveConfig.worldSettings;
		seed = worldSaveConfig.worldSettings.seed;
		terrainChunkCountY = worldSaveConfig.worldSettings.terrainChunkCountY;
		chunkCountY = (byte)(terrainChunkCountY + chunkCountYExtraSpacing);
		totalVoxelsY = (chunkCountY * chunkVoxelSize);
		int maxTerrainHeightInMeters = terrainChunkCountY * metersPerChunk;
		int maxTerrainHeightInTerrainUnits = maxTerrainHeightInMeters * terrainUnitsPerMeter;
		ushort caveStartYLevelTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.cavesStartTerrainHeightRatio);
		ushort explicitWaterLevelTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.explicitWaterLevelTerrainHeightRatio);
		ushort cavesWaterHeightTerrainUnits = (ushort)(maxTerrainHeightInTerrainUnits * settings.cavesWaterLevelTerrainHeightRatio);
		// init cave gen helper
		CaveGeneratorHelperParams caveGenHelperParams = new CaveGeneratorHelperParams {
			seed = seed,
			thresholdCaves = settings.cavesSpaceAmount,
			thresholdTunnelNodes = settings.cavesTunnelsChance,
			thresholdEntranceNodes = settings.cavesTunnelEntrancesChance,
			caveStartYLevelTerrainUnits = caveStartYLevelTerrainUnits
		};
		caveGenerationHelper = new CaveGenerationHelper(caveGenHelperParams);
		
		waitingForFirstMeshedChunk = true; // ui switches to game only after first column geometry is generated
		// initialize tracking collections for iterative region - chunk system
		loadedRegions = [];
		generatedRegions = [];
		loadedColumns = [];
		generatedColumns = [];
        meshedColumnLods[0] = [];
        meshedColumnLods[1] = [];
        meshedColumnLods[2] = [];
        meshedColumnLods[3] = [];
		columnLods = new Dictionary<(int, int), LodLevel>();
		// initialize voxel storage and cave gen helper
		voxelStorage = new VoxelStorage(metersPerChunk, voxelsPerMeter, chunkCountY);
		WorldGeneratorParams worldGenParams = new WorldGeneratorParams // parameters for world generator
		{
			seed = seed,
			maxTerrainHeightInTerrainUnits = maxTerrainHeightInTerrainUnits,
			voxelsPerMeter = voxelsPerMeter,
			metersPerRegion = metersPerRegion,
			metersPerChunk = metersPerChunk,
			unitsPerMeter = terrainUnitsPerMeter,
			cavesStartYLevelTerrainUnits = caveStartYLevelTerrainUnits,
			cavesEnabled = settings.cavesEnabled,
			caveGenerationHelper = caveGenerationHelper,
			lakeSize = LakeSize.FromLakeSizeType(settings.lakeSize),
			waterAvailEffectStrength = WaterAvailEffectStrength.FromWaterAvailEffectStrengthType(settings.waterAvailabilityStrength),
			heightNoiseConfig = HeightNoiseConfig.FromHeightNoiseConfigType(settings.heightNoiseConfig),
			vegetationChance = VegetationChance.FromOverallVegetationChanceType(settings.overallVegetationChance),
			explicitWaterLevelTerrainUnits = explicitWaterLevelTerrainUnits,
			maxRiverLength = settings.maxRiverLength,
			explicitWaterAvailabilityMax = settings.explicitWaterAvailabilityMaxEffect,
			areaAgeThresholds = settings.areaAgeThresholds,
			areaHeightThresholds =  settings.areaHeightThresholds,
			areaWaterAvailabilityThresholds = settings.areaWaterAvailabilityThresholds,
			waterLilyChance = settings.waterLilyChance,
			waterReedsChance = settings.waterReedsChance,
			snowOccurenceThreshold = settings.snowChance
		};
		// initialize world generator service with world generator
		worldGeneratorService = new WorldGeneratorService(worldServiceThreads, worldGenParams);
		VoxelGeneratorParams voxelGenParams = new VoxelGeneratorParams
		{
			voxelStorage =  voxelStorage,
			worldGeneratorService = worldGeneratorService,
			storageService = storageService,
			caveGenerationHelper = caveGenerationHelper,
			seed = seed,
			metersPerRegion = metersPerRegion,
			metersPerChunk = metersPerChunk,
			voxelsPerMeter = voxelsPerMeter,
			terrainUnitsPerMeter = terrainUnitsPerMeter,
			caveStartYLevelTerrainUnits = caveStartYLevelTerrainUnits,
			cavesWaterHeightTerrainUnits = cavesWaterHeightTerrainUnits,
			cavesEnabled = settings.cavesEnabled,
			stalactiteChance = settings.cavesStalactitesChance,
			waterfallChance = settings.cavesWaterfallChance
		};
		// initialize remaining services
		voxelGeneratorService = new VoxelGeneratorService(voxelServiceThreads, voxelGenParams);
		geometryGeneratorService = new GeometryGeneratorService(voxelStorage, voxelGeneratorService, geometryServiceThreads, lodCount, chunkCountY);
		worldDisplayService = new WorldDisplayService(geometryGeneratorService, chunkCountY, waterMaterial, blockMaterialBasic, blockMaterialVariance, voxelWorld);
		voxelEditService = new VoxelEditService(voxelStorage, storageService, worldDisplayService, voxelsPerMeter, chunkCountY, (byte)chunkVoxelSize);
		// and subscribe to their events
		geometryGeneratorService.SubscribeToVoxelEditService(voxelEditService);
		voxelEditService.SubscribeOnEditFailed(OnEditingProcessed);
		worldGeneratorService.SubscribeOnRegionGenerated(OnRegionGenerated);
		voxelGeneratorService.SubscribeOnChunkColumnGenerated(OnChunkColumnGenerated);
		geometryGeneratorService.SubscribeOnColumnGeometryGenerated(OnChunkColumnMeshed);
		geometryGeneratorService.SubscribeOnEditingProcessed(OnEditingProcessed);
		// init, configure and run model generation
		modelService = new ModelService(seed, modelServiceThreads);
		modelService.SubscribeOnModelsGenerated(OnModelsGenerated);
		VoxelModelDefinitions.InsertVoxelModelDefinitions(modelService);
		menu.ShowCenteredMessageLoading($"Generating models ... (0/{modelService.GetTotalModelsCount()})");
		generatingModels = true;
		modelService.GenerateModels();
        weatherEnvManager.Start(worldGeneratorService, worldSaveConfig.worldSettings.seed, worldSaveConfig.sunAngle, worldSaveConfig.weatherSimulationTime);
        player.SetTorchVisibility(worldSaveConfig.torchEnabled);
        
        // player placing and positioning
        if (newGame)
        {
            // player will be placed at 0,0,0 position in new world
            player.TeleportPlayer(new Vector3Double(0, 0, 0));
            playerNotPlaced = true;
        }
        else
        {
            // or last position in loaded worlds
            player.TeleportPlayer(worldSaveConfig.lastPlayerPosition);
            weatherEnvManager.OnPlayerPositionChanged();
            CheckPlanOriginShift();
            weatherEnvManager.MoveLights();
        }
	}

	/**
	 * Unloads currently active world by disposing of all data instances of services and generators.
	 */
	private void UnloadWorld()
	{
		// need to stop all generation tasks, disable threads, clear storage and services / generators
		iterativeRuns = false;

        weatherEnvManager.Stop();
        
		voxelEditService = null;
		
		if (worldDisplayService != null)
		{
			worldDisplayService.Dispose();
			worldDisplayService = null;
		}
		
		if (geometryGeneratorService != null)
		{
			geometryGeneratorService.Dispose();
			geometryGeneratorService = null;
		}
		
		if (voxelGeneratorService != null)
		{
			voxelGeneratorService.Dispose();
			voxelGeneratorService = null;
		}
		
		if (worldGeneratorService != null)
		{
			worldGeneratorService.Dispose();
			worldGeneratorService = null;
		}

		caveGenerationHelper = null;
		
		voxelStorage  = null;
		
		if (worldDisplayService != null)
		{
			worldDisplayService.Dispose();
			worldDisplayService = null;
		}

		storageService.Dispose();

		if (modelService != null)
		{
			modelService.Dispose();
			modelService = null;
		}
	
		loadedRegions = null;
		generatedRegions = null;
		loadedColumns = null;
		generatedColumns = null;
        meshedColumnLods[0] = null;
        meshedColumnLods[1] = null;
        meshedColumnLods[2] = null;
        meshedColumnLods[3] = null;
		columnLods = null;
		
		GC.Collect();
	}
	
	/**
	 * Configures LOD distances based on supplied values.
	 * For changes of values from UI and loaded application settings.
	 */
	public void SetLodConfiguration(int[] distances)
	{
        if (lodDistances == null || lodDistances.Length != lodCount)
        {
            GD.PrintErr("Incorrect number of lod distances");
        }
        
        lodDistances = distances;
		
		CalculateRegionChunksDistances(); // needs to recalculate all dependent distances for the iterative system
        
		if (iterativeRuns)
		{
			CalculateRegionsChunksAsync(player.GetRealPosition());
		}
	}

	/**
	 * Recalculates distances for the iterative generation system region - chunk calculation step.
	 * Includes calculation of squared values of chunk system distances for later circular chunk system checks.
	 */
	private void CalculateRegionChunksDistances()
	{
		lodDistanceMax = lodDistances[lodCount-1];
		regionTerrainTriggerDistance = regionTerrainMin + lodDistanceMax;
		regionFeaturesTriggerDistance = regionFeaturesMin + lodDistanceMax;
		columnPreparationDistance = lodDistanceMax + columnPreparationDistanceAddition;
		columnVoxelizationDistance = lodDistanceMax + columnVoxelizationDistanceAddition;
		regionTriggerDistanceUnload = regionTerrainTriggerDistance + regionUnloadMargin;
		columnStorageDistanceUnload = columnPreparationDistance + columnStorageUnloadMargin;
        columnGeneratorDistCancel = columnVoxelizationDistance + columnGeneratorCancelMargin;
		// squared distances in chunk units for circular chunk system recalculation
		columnPrepDistSquared = (int)Math.Pow(columnPreparationDistance/(double)metersPerChunk, 2);
		columnStorageDistUnloadSquared = (int)Math.Pow(columnStorageDistanceUnload/(double)metersPerChunk, 2);
		columnVoxDistSquared = (int)Math.Pow(columnVoxelizationDistance/(double)metersPerChunk, 2);
        columnGeneratorDistCancelSquared = (int)Math.Pow(columnGeneratorDistCancel/(double)metersPerChunk, 2);
		
		for (int lod = 0; lod < lodCount; lod++)
		{
			lodDistSquared[lod] = (int)Math.Pow(lodDistances[lod]/(double)metersPerChunk, 2);
			columnMeshingLodDistances[lod] = lodDistances[lod] + columnMeshingDistanceAddition;
			columnMeshingLodDistSquared[lod] = (int)Math.Pow(columnMeshingLodDistances[lod]/(double)metersPerChunk, 2);
			// unload
			columnMeshingLodUnloadDistances[lod] = columnMeshingLodDistances[lod] + columnGeometryUnloadMargin;
			columnMeshingLodUnloadDistSquared[lod] = (int)Math.Pow(columnMeshingLodUnloadDistances[lod]/(double)metersPerChunk, 2);
		}
	}

	/**
	 * Starts up asynchronous task that runs CalculateRegionsChunks method.
	 * Only a single task can run at the same time.
	 */
	private void CalculateRegionsChunksAsync(Vector3Double cameraPosition)
	{
		if (calculateRegionsChunksTask != null && !calculateRegionsChunksTask.IsCompleted)
			return;

		calculateRegionsChunksTask = Task.Run(() => CalculateRegionsChunks(cameraPosition));
	}

	/**
	 * Calculates regions and columns that on all levels of the hierarchical system should be now displayed.
	 * And supplies tasks to all levels of the system to change its state to the new one.
	 * Works with centered circular areas (apart from terrain which still uses rectangles).
	 */
	private void CalculateRegionsChunks(Vector3Double cameraPosition)
	{
		// terrain still rectangular
		// regions loading - terrain
		var (camRegionX, camRegionZ) = worldGeneratorService.WorldPosToRegionCoords(cameraPosition.x, cameraPosition.z);
		Vector3Double minPos = cameraPosition - new Vector3Double(regionTerrainTriggerDistance, 0, regionTerrainTriggerDistance);
		Vector3Double maxPos = cameraPosition + new Vector3Double(regionTerrainTriggerDistance, 0, regionTerrainTriggerDistance);
		var (minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		var (maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		// generate tasks if not already present
		for (int regionX = minRegionX; regionX <= maxRegionX; regionX++)
		{
			for (int regionZ = minRegionZ; regionZ <= maxRegionZ; regionZ++)
			{
				if (!loadedRegions.Contains((regionX, regionZ)))
				{
					loadedRegions.Add((regionX, regionZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(regionX - camRegionX) + Math.Abs(regionZ - camRegionZ);
					worldGeneratorService.AddTask(new WorldGenTask(REGION_TASK_TYPE.GENERATE_TERRAIN, regionX, regionZ, priority));
				}
			}
		}
		
		// regions loading - features
		minPos = cameraPosition - new Vector3Double(regionFeaturesTriggerDistance, 0, regionFeaturesTriggerDistance);
		maxPos = cameraPosition + new Vector3Double(regionFeaturesTriggerDistance, 0, regionFeaturesTriggerDistance);
		(minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		(maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		// generate tasks if not already present
		for (int regionX = minRegionX; regionX <= maxRegionX; regionX++)
		{
			for (int regionZ = minRegionZ; regionZ <= maxRegionZ; regionZ++)
			{
				if (!generatedRegions.Contains((regionX, regionZ)))
				{
					generatedRegions.Add((regionX, regionZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(regionX - camRegionX) + Math.Abs(regionZ - camRegionZ);
					worldGeneratorService.AddTask(new WorldGenTask(REGION_TASK_TYPE.GENERATE_FEATURES, regionX, regionZ, priority));
				}
			}
		}
		
		// regions unloading
		minPos = cameraPosition - new Vector3Double(regionTriggerDistanceUnload, 0, regionTriggerDistanceUnload);
		maxPos = cameraPosition + new Vector3Double(regionTriggerDistanceUnload, 0, regionTriggerDistanceUnload);
		(minRegionX, minRegionZ) = worldGeneratorService.WorldPosToRegionCoords(minPos.x, minPos.z);
		(maxRegionX, maxRegionZ) = worldGeneratorService.WorldPosToRegionCoords(maxPos.x, maxPos.z);
		HashSet<(int x, int z)> regionsToUnload = [];
		// actual region removal happens only on the larger rectangle of loaded regions that only cover the terrain generation phase of regions
		foreach (var (regionX, regionZ) in loadedRegions)
		{
			if (regionX < minRegionX || regionX > maxRegionX || regionZ < minRegionZ || regionZ > maxRegionZ)
			{
				regionsToUnload.Add((regionX, regionZ));
			}
		}
		foreach (var region in regionsToUnload)
		{
			loadedRegions.Remove(region);
			generatedRegions.Remove(region);
			worldGeneratorService.UnloadRegion(region.x, region.z);
		}
		regionsToUnload.Clear();
		
		// chunk columns loading
		var (camChunkX, camChunkZ) = voxelStorage.WorldPosToChunkCoords(cameraPosition.x, cameraPosition.z);
		minPos = cameraPosition - new Vector3Double(columnPreparationDistance, 0, columnPreparationDistance);
		maxPos = cameraPosition + new Vector3Double(columnPreparationDistance, 0, columnPreparationDistance);
		var (minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		var (maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		// create chunk columns in voxel storage if not present
		for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
		{
			for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
			{
				if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) <= columnPrepDistSquared &&
				    !loadedColumns.Contains((chunkX, chunkZ)))
				{
					loadedColumns.Add((chunkX, chunkZ));
					voxelStorage.CreateChunkColumn(chunkX, chunkZ);
				}
			}
		}
		// chunk columns unloading
		HashSet<(int x, int z)> columnsToUnload = [];
		// for loaded columns with cleanup of voxel storage
		foreach (var (chunkX, chunkZ) in loadedColumns)
		{
			if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) > columnStorageDistUnloadSquared)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		foreach (var chunk in columnsToUnload)
		{
			loadedColumns.Remove(chunk);
			voxelStorage.RemoveChunkColumn(chunk.x, chunk.z);
			GD.Print($"Unloaded chunk column at {chunk.x}, {chunk.z} from voxel storage");
		}
        
        // voxelization unloading
		// for generated active chunks in voxel generator, needs to be split, otherwise voxel storage would have
		// a set of incorrect canceled tasks and some columns would never be generated
        columnsToUnload.Clear();
		foreach (var (chunkX, chunkZ) in generatedColumns)
		{
			if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) > columnGeneratorDistCancelSquared)
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		foreach (var chunk in columnsToUnload)
		{
			// remove from generated columns
			generatedColumns.Remove(chunk);
		}
		voxelGeneratorService.UnloadColumns(columnsToUnload);
		columnsToUnload.Clear();
		
		// voxelization loading
		minPos = cameraPosition - new Vector3Double(columnVoxelizationDistance, 0, columnVoxelizationDistance);
		maxPos = cameraPosition + new Vector3Double(columnVoxelizationDistance, 0, columnVoxelizationDistance);
		(minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
		(maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
		// plan voxelization of not yet voxelized columns
		for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
		{
			for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
			{
				if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) <= columnVoxDistSquared &&
				    !generatedColumns.Contains((chunkX, chunkZ)))
				{
					generatedColumns.Add((chunkX, chunkZ));
					// calculate priority with manhattan distance
					int priority = Math.Abs(chunkX - camChunkX) + Math.Abs(chunkZ - camChunkZ);
					voxelGeneratorService.AddTask(new ChunkColumnTask(chunkX, chunkZ, priority));
				}
			}
		}
        
        // geometry unloading
        for (int lod = 0; lod < lodCount; lod++)
        {
            foreach (var (chunkX, chunkZ) in meshedColumnLods[lod])
            {
	            if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) > columnMeshingLodUnloadDistSquared[lod])
                {
                    columnsToUnload.Add((chunkX, chunkZ));
                }
            }
		
            foreach (var chunk in columnsToUnload)
            {
                meshedColumnLods[lod].Remove(chunk);
            }
            // unload geometry in one pass
            geometryGeneratorService.UnloadColumns(columnsToUnload, (LodLevel)lod);
            columnsToUnload.Clear();
        }
		
        // geometry loading
        for (int lod = 0; lod < lodCount; lod++)
        {
            minPos = cameraPosition - new Vector3Double(columnMeshingLodDistances[lod], 0, columnMeshingLodDistances[lod]);
            maxPos = cameraPosition + new Vector3Double(columnMeshingLodDistances[lod], 0, columnMeshingLodDistances[lod]);
            (minChunkX, minChunkZ) = voxelStorage.WorldPosToChunkCoords(minPos.x, minPos.z);
            (maxChunkX, maxChunkZ) = voxelStorage.WorldPosToChunkCoords(maxPos.x, maxPos.z);
            // plan generation of not yet planned geometry
            for (int chunkX = minChunkX; chunkX <= maxChunkX; chunkX++)
            {
                for (int chunkZ = minChunkZ; chunkZ <= maxChunkZ; chunkZ++)
                {
	                if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) <= columnMeshingLodDistSquared[lod] &&
	                    !meshedColumnLods[lod].Contains((chunkX, chunkZ)))
                    {
                        meshedColumnLods[lod].Add((chunkX, chunkZ));
                        // calculate priority with manhattan distance
                        int priority = Math.Abs(chunkX - camChunkX) + Math.Abs(chunkZ - camChunkZ);
                        geometryGeneratorService.AddNormalTask(new ChunkColumnGeometryTask(GEOMETRY_TASK_TYPE.GENERATE, (LodLevel)lod, chunkX, uint.MaxValue, chunkZ, priority));
                    }
                }
            }
        }
        
		// calculate target lods for viewing
        Vector3Double minPosLod3 = cameraPosition - new Vector3Double(lodDistances[3], 0, lodDistances[3]);
        Vector3Double maxPosLod3 = cameraPosition + new Vector3Double(lodDistances[3], 0, lodDistances[3]);
        var (minChunkXLod3, minChunkZLod3) = voxelStorage.WorldPosToChunkCoords(minPosLod3.x, minPosLod3.z);
        var (maxChunkXLod3, maxChunkZLod3) = voxelStorage.WorldPosToChunkCoords(maxPosLod3.x, maxPosLod3.z);
		// recalculate the lods for chunk columns
		for (int chunkX = minChunkXLod3; chunkX <= maxChunkXLod3; chunkX++)
		{
			for (int chunkZ = minChunkZLod3; chunkZ <= maxChunkZLod3; chunkZ++)
			{
				// switch to correct lod
				LodLevel correctLod = LodLevel.UNLOADED;
				double totalDistSquared = Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2);
				// is in circular area
				if (totalDistSquared > lodDistSquared[3])
				{
					continue;
				}
				
				if (totalDistSquared <= lodDistSquared[0])
				{
					correctLod = LodLevel.LOD0;
				}
				else
				if (totalDistSquared <= lodDistSquared[1])
				{
					correctLod = LodLevel.LOD1;
				}
				else
				if (totalDistSquared <= lodDistSquared[2])
				{
					correctLod = LodLevel.LOD2;
				}
				else
				if (totalDistSquared <= lodDistSquared[3])
				{
					correctLod = LodLevel.LOD3;
				}

				// new column to display
				if (!columnLods.ContainsKey((chunkX, chunkZ)))
				{
					columnLods[(chunkX, chunkZ)] = correctLod;
					worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.DISPLAY, chunkX, uint.MaxValue, chunkZ, correctLod));
				}
				else
				{ // updating displayed one
					LodLevel currentLod = columnLods[(chunkX, chunkZ)];
					if (currentLod != correctLod)
					{
						columnLods[(chunkX, chunkZ)] = correctLod;
						worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.DISPLAY, chunkX, uint.MaxValue, chunkZ, correctLod));
					}
				}
			}
		}
		
		// displayed columns unloading
		foreach (var (chunkX, chunkZ) in columnLods.Keys)
		{
			if (Math.Pow(chunkX - camChunkX, 2) + Math.Pow(chunkZ - camChunkZ, 2) > lodDistSquared[3])
			{
				columnsToUnload.Add((chunkX, chunkZ));
			}
		}
		
		foreach (var column in columnsToUnload)
		{
			columnLods.Remove(column);
			worldDisplayService.AddTask(new WorldDisplayTask(WorldDisplayTaskType.HIDE, column.x, uint.MaxValue, column.z, LodLevel.UNLOADED));
		}
	}
	
	/**
	 * Yields current thread to world display service to apply pre-processed DISPLAY / UPDATE tasks.
	 * The amount of applied tasks depends on the current frame time, reducing stuttering.
	 */
	private void ProcessCompletedMeshes(double delta)
	{
        Stopwatch stopwatch = Stopwatch.StartNew();
        while (true)
        {
            worldDisplayService.ProcessDisplayUpdateTask();
            if (stopwatch.ElapsedMilliseconds >= delta * 1000 / chunkUpdatesDeltaDivider)
            {
                break;
            }
        }
	}
	
	/**
	 * Fired when player camera changes position.
	 * Repositions sun based on player position, if it is not in automatic sun cycle.
	 * Starts up region - chunk recalculation and check for origin shift process with debouncing.
	 */
	private void OnCameraPositionChanged()
	{
		if (!iterativeRuns)
			return;
		
		// this debounce is not as necessary now, when only a single async thread can run the calculation at once
		double currentTime = Time.GetUnixTimeFromSystem();
		if (currentTime - lastLodUpdateTime < lodUpdateInterval)
			return;
		
		lastLodUpdateTime = currentTime;
		Vector3Double playerPosition = player.GetRealPosition();
		CalculateRegionsChunksAsync(playerPosition);
		
		CheckPlanOriginShift();
	}
	
	/**
	 * Performs origin shift change with the precomputed offset vector.
	 */
	private void PerformOriginShift()
	{
		// needs to freeze player, move the world and then unfreeze the player
		player.FreezeBeforeOriginShift();
		worldDisplayService.ApplyOriginShift(currentOriginShiftOffsetXZ);
		player.ApplyOriginShift(currentOriginShiftOffsetXZ);
		player.UnfreezeAfterOriginShift();
	}
	
	/**
	 * Checks whether the origin shift vector should change based on different position of player/camera.
	 * Shifting is done on a centered XZ grid of cells. When player moves across cell borders, a different
	 * shift vector is computed so that the whole world and the player would always be placed around the center
	 * of engine coordinate system to reduce floating point precision errors during rendering and physics.
	 * The cell with offset 0,0 is at -halfCell to halfCell area in both X and Z dimension.
	 */
	private void CheckPlanOriginShift()
	{
		if (originShiftPlanned)
			return;
		
		Vector3Double playerPosition = player.GetRealPosition();

		// calculate current cell coordinates of the player
		int cellX = (int)Math.Floor((playerPosition.x + originShiftHalfCell) / originShiftGridCellSize);
		int cellZ = (int)Math.Floor((playerPosition.z + originShiftHalfCell) / originShiftGridCellSize);

		// new origin offset
		int newOffsetX = - cellX * originShiftGridCellSize;
		int newOffsetZ = - cellZ * originShiftGridCellSize;

		// trigger shift, when cells differ
		if (newOffsetX == currentOriginShiftOffsetXZ.x && newOffsetZ == currentOriginShiftOffsetXZ.z)
			return;

		Vector3Int newOriginShift = new Vector3Int(newOffsetX, 0, newOffsetZ);
		currentOriginShiftOffsetXZ = newOriginShift;
		originShiftPlanned = true;
	}

	/**
	 * Teleports player to specified real (non-shifted) position
	 */
	public void TeleportPlayer(Vector3Double realPosition)
	{
		if (!iterativeRuns)
			return;
		
		// reset to bogus value to always trigger a shift offset recalculation
		currentOriginShiftOffsetXZ = new Vector3Int(int.MaxValue, int.MaxValue, int.MaxValue);
		player.TeleportPlayer(realPosition);
		originShiftPlanned = false;
		CheckPlanOriginShift();
		// necessary to recalculate active regions - chunks
		CalculateRegionsChunksAsync(realPosition);
	}
	
	/**
	 * Triggered when the menu changes state to allow / disallow player voxel editing.
	 */
	public void OnEditingStatusChange(bool enabled, bool signalEnabled)
	{
		editingEnabled = enabled;
		allowEditDoneSignal = signalEnabled;
	}
	
	/**
	 * Periodic engine yielded invocation.
	 * Yields itself to the world display service to apply its pre-processed tasks - display, update and cleanup.
	 * Performs planned origin shift update.
	 * Processes updates to the debug menu, allows toggling of several features (debug menu, wireframe, sun movement).
	 * Triggers voxel editing based on user input and runs the sun movement code.
	 */
	public override void _Process(double delta)
	{
		// show model generation progress
		if (generatingModels)
		{
			uint totalModels = modelService.GetTotalModelsCount();
			uint remainingModels = modelService.GetRemainingTasksCount();
			menu.ShowCenteredMessageLoading($"Generating models... {totalModels - remainingModels}/{totalModels}");
		}

		if (iterativeRuns)
		{
            // column display management
            // hide columns
            worldDisplayService.ProcessPlannedMeshUnloads();
            // process column display and updates
            ProcessCompletedMeshes(delta);
            // perform origin shift when planned
            if (originShiftPlanned)
            {
                PerformOriginShift();
                originShiftPlanned = false;
            }
            // weather simulation
            weatherEnvManager.SimulationStep();
            
			// update debug menu with stats
			var worldGenActiveRegions = worldGeneratorService.GetActiveRegionsCount();
			var worldGenRemainingTasks = worldGeneratorService.GetRemainingTasksCount();
			var worldGenLockedTasks = worldGeneratorService.GetLockedTasksCount();
			var worldGenWorkingTasks = worldGeneratorService.GetActiveThreadsCount();
			var voxelGenActiveColumns = voxelGeneratorService.GetActiveColumnsCount();
			var voxelGenRemainingTasks = voxelGeneratorService.GetRemainingTasksCount();
			var voxelGenLockedTasks = voxelGeneratorService.GetLockedTasksCount();
			var voxelGenWaitingNeighborsCount = voxelGeneratorService.GetWaitingNeighborsCount();
			var modelGenRemainingTasks = modelService.GetRemainingTasksCount();
			var geometryGenRemainingTasks = geometryGeneratorService.GetRemainingTasksCount();
			var geometryGenLockedTasks = geometryGeneratorService.GetLockedTasksCount();
			var geometryGenActiveColumns = geometryGeneratorService.GetActiveColumnsCount();
            List<long> lodResults = geometryGeneratorService.GetAverageChunkLodGenerationTime();
			var meshViewDisplayedColumns = worldDisplayService.GetDisplayedColumnsCount();
			var meshViewRemainingTasks = worldDisplayService.GetRemainingTasksCount();
			var meshViewLockedTasks = worldDisplayService.GetLockedTasksCount();
			Vector3Double realPlayerPosition = player.GetRealPosition();
			var cameraChunk = new Vector3Int(
				(int)Math.Floor(realPlayerPosition.x / metersPerChunk),
				(int)Math.Floor(realPlayerPosition.y / metersPerChunk),
				(int)Math.Floor(realPlayerPosition.z / metersPerChunk)
			);
			Vector3 shiftedPlayerPosition = player.Position;

			fpsLabel.Text = $"WORLD GEN (A/W/R/L): {worldGenActiveRegions}/{worldGenWorkingTasks}/{worldGenRemainingTasks}/{worldGenLockedTasks}\n" +
							$"VOXEL GEN (A/R/L): {voxelGenActiveColumns}/{voxelGenRemainingTasks}/{voxelGenLockedTasks}/{voxelGenWaitingNeighborsCount}\n" +
							$"GEOMT GEN (A/R/L): {geometryGenActiveColumns}/{geometryGenRemainingTasks}/{geometryGenLockedTasks}\n" +
							$"MESH  GEN: {lodResults[0]}/{lodResults[1]}/{lodResults[2]}/{lodResults[3]} ms average\n" +
							$"MESH VIEW (A/R/L): {meshViewDisplayedColumns}/{meshViewRemainingTasks}/{meshViewLockedTasks}\n" +
							$"MODEL GEN (R): {modelGenRemainingTasks}\n" +
							$"CAMERA CHUNK: {cameraChunk.x}, {cameraChunk.y}, {cameraChunk.z}\n" +
							$"CAMERA POSITION: {Math.Round(realPlayerPosition.x, 2)}, {Math.Round(realPlayerPosition.y, 2)}, {Math.Round(realPlayerPosition.z, 2)}\n" +
							$"ORIGIN SHIFT OFFSET: {currentOriginShiftOffsetXZ.x}, {currentOriginShiftOffsetXZ.z}\n" +
							$"SHIFTED CAMERA POSITION: {Math.Round(shiftedPlayerPosition.X, 2)}, {Math.Round(shiftedPlayerPosition.Y, 2)}, {Math.Round(shiftedPlayerPosition.Z, 2)}";

            // toggle sun automatic cycle
            if (Input.IsActionJustPressed("toggle_sun"))
            {
                weatherEnvManager.SetDayCycleStatus(!weatherEnvManager.dayCycleEnabled);
                menu.UpdateInGameDayCycleState(weatherEnvManager.dayCycleEnabled);
            }
            // toggle weather simulation
            if (Input.IsActionJustPressed("toggle_weather"))
            {
                weatherEnvManager.SetWeatherSimulationStatus(!weatherEnvManager.weatherCycleEnabled);
                menu.UpdateInGameWeatherSimulationState(weatherEnvManager.weatherCycleEnabled);
            }
		}
		// toggle debug menu
		if (Input.IsActionJustPressed("debug_menu"))
		{
			fpsLabel.SetVisible(!fpsLabel.Visible);
		}
		// toggle wireframe display
		if (Input.IsActionJustPressed("toggle_wireframe"))
		{
			switch (displayMode)
			{
				case DisplayMode.DEFAULT:
					GetViewport().DebugDraw = Viewport.DebugDrawEnum.Wireframe;
					displayMode = DisplayMode.WIREFRAME;
					break;
				case DisplayMode.WIREFRAME:
					GetViewport().DebugDraw = Viewport.DebugDrawEnum.Disabled;
					displayMode = DisplayMode.DEFAULT;
					break;
			}
		}
		
		// block placement and removal
		if (editingEnabled)
		{
			if (Input.IsActionJustReleased("destroy_block"))
			{
				Vector3 lookAtDirection = player.GetLookAtDirection();
				Vector3Double playerPosition = player.GetCenteredCameraRealPosition();
				
				// block destruction - async
				editingEnabled = false;
				voxelEditService.RaycastVoxelEditAsync(playerPosition, lookAtDirection, maxEditingDistance, editingVoxelType, editingVoxelSize, false);
			}
			else if (Input.IsActionJustReleased("place_block"))
			{
				Vector3 lookAtDirection = player.GetLookAtDirection();
				Vector3Double playerPosition = player.GetCenteredCameraRealPosition();
				
				// block placement - async
				editingEnabled = false;
				voxelEditService.RaycastVoxelEditAsync(playerPosition, lookAtDirection, maxEditingDistance, editingVoxelType, editingVoxelSize, true);
			}
		}
	}

	/**
	 * Resets state of the app when starting new world
	 */
	public void ResetWorldPlayerSettings()
	{
		GetViewport().DebugDraw = Viewport.DebugDrawEnum.Disabled;
		displayMode = DisplayMode.DEFAULT;
	}
	
	/**
	 * Toggles mouse capture mode.
	 * In game vs menus.
	 */
	private void ToggleMouseCaptureMode()
	{
		mouseModeCaptured = !mouseModeCaptured;
		if (mouseModeCaptured)
		{
			Input.MouseMode = Input.MouseModeEnum.Captured;
		}
		else
		{
			Input.MouseMode = Input.MouseModeEnum.Visible;
		}
	}
	
	/**
	 * Signalizes that processing of last user voxel edit has finished.
	 * Re-enables editing if allowed.
	 */
	private void OnEditingProcessed()
	{
		if (allowEditDoneSignal)
		{
			editingEnabled = true;
		}
	}

	/**
	 * Changing voxel type for editing.
	 */
	public void OnVoxelEditTypeChanged(VoxelType voxelType)
	{
		editingVoxelType = voxelType;
	}
	
	/**
	 * Changing editing voxel size.
	 */
	public void OnVoxelEditSizeChanged(int value)
	{
		editingVoxelSize = (byte)Math.Pow(2, value - 1);
	}
	
	//NOTE: In both world exit cases it is the menu code that triggers world config save with last player position.

	/**
	 * Unloads current world as it leaves game for title menu.
	 */
	public void OnExitToTitleMenu()
	{
		UnloadWorld();
	}

	/**
	 * Unloads current world and quits.
	 */
	public void OnExit()
	{
		UnloadWorld();
		GetTree().Quit();
	}
}
